// Tigercat.Admin.Vue/src/components/PageHeader.vue
<script setup lang="ts">
import { Card, Text, Tag } from '@expcat/tigercat-vue'
import Icon from './Icon.vue'

interface PageHeaderTag {
  label: string
  color: 'blue' | 'green' | 'red' | 'purple' | 'orange'
}

const props = defineProps<{
  title: string
  subtitle: string
  icon: string
  tags?: PageHeaderTag[]
}>()
</script>

<template>
  <Card class="overflow-hidden">
    <div class="relative">
      <div class="p2-page-accent absolute inset-0 -m-4"></div>
      <div class="relative flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div class="min-w-0">
          <div class="flex items-center gap-3 mb-2">
            <div class="p2-icon-chip flex h-12 w-12 shrink-0 items-center justify-center">
              <Icon :name="props.icon" :size="24" />
            </div>
            <div class="min-w-0">
              <Text size="lg" weight="bold" class="p2-text-primary">
                {{ props.title }}
              </Text>
              <Text size="sm" color="secondary">
                {{ props.subtitle }}
              </Text>
            </div>
          </div>
        </div>
        <div v-if="props.tags?.length" class="hidden sm:flex items-center gap-2">
          <Tag v-for="tag in props.tags" :key="tag.label" :color="tag.color" size="sm">
            {{ tag.label }}
          </Tag>
        </div>
      </div>
    </div>
  </Card>
</template>

// Tigercat.Admin.React/src/components/PageHeader.tsx
import { Card, Tag, Text } from '@expcat/tigercat-react';
import type { ReactNode } from 'react';

export type PageHeaderTag = {
  label: string;
  color: 'blue' | 'green' | 'red' | 'purple' | 'orange';
};

interface PageHeaderProps {
  title: string;
  subtitle: string;
  icon: ReactNode;
  tags?: PageHeaderTag[];
}

export function PageHeader({ title, subtitle, icon, tags }: PageHeaderProps) {
  return (
    <Card className="overflow-hidden">
      <div className="relative">
        <div className="p2-page-accent absolute inset-0 -m-4" />
        <div className="relative flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="min-w-0">
            <div className="flex items-center gap-3 mb-2">
              <div className="p2-icon-chip flex h-12 w-12 shrink-0 items-center justify-center">
                {icon}
              </div>
              <div className="min-w-0">
                <Text size="lg" weight="bold" className="p2-text-primary">
                  {title}
                </Text>
                <Text size="sm" color="secondary">
                  {subtitle}
                </Text>
              </div>
            </div>
          </div>
          {tags && tags.length > 0 && (
            <div className="hidden sm:flex items-center gap-2">
              {tags.map((tag) => (
                <Tag key={tag.label} color={tag.color} size="sm">
                  {tag.label}
                </Tag>
              ))}
            </div>
          )}
        </div>
      </div>
    </Card>
  );
}
