// Tigercat.Admin.Vue/src/pages/CalendarPage.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Card, Text, Tag, Button, Message } from '@expcat/tigercat-vue'
import { Calendar } from '@expcat/tigercat-vue/Calendar'
import { Countdown } from '@expcat/tigercat-vue/Countdown'
import { Statistic } from '@expcat/tigercat-vue/Statistic'
import { Badge } from '@expcat/tigercat-vue/Badge'
import { Popover } from '@expcat/tigercat-vue/Popover'
import { List } from '@expcat/tigercat-vue/List'
import { Drawer } from '@expcat/tigercat-vue/Drawer'
import { DatePicker } from '@expcat/tigercat-vue/DatePicker'
import { TimePicker } from '@expcat/tigercat-vue/TimePicker'
import { RadioGroup } from '@expcat/tigercat-vue/RadioGroup'
import { Radio } from '@expcat/tigercat-vue/Radio'
import { Input } from '@expcat/tigercat-vue'
import type {
  ListItem,
  DatePickerModelValue,
  TimePickerModelValue,
} from '@expcat/tigercat-core'
import PageHeader from '../components/PageHeader.vue'
import MutedPanel from '../components/MutedPanel.vue'
import Icon from '../components/Icon.vue'
import {
  calendarQueryRange,
  createCalendarEvent,
  fetchCalendarEvents,
  formatCalendarDate,
  type CalendarEvent,
  type CalendarEventType,
} from '../utils/calendar'

const TYPE_META: Record<CalendarEventType, { label: string; variant: 'primary' | 'warning' | 'danger' | 'info' }> = {
  meeting: { label: '会议', variant: 'primary' },
  review: { label: '评审', variant: 'warning' },
  release: { label: '发布', variant: 'danger' },
  reminder: { label: '提醒', variant: 'info' },
}

const events = ref<CalendarEvent[]>([])
const loading = ref(false)
const submitting = ref(false)
const selectedDate = ref<Date>(new Date('2026-06-29T00:00:00'))

const readErrorMessage = (error: unknown, fallback: string) =>
  error instanceof Error && error.message ? error.message : fallback

function onDateChange(value: unknown) {
  if (value instanceof Date) selectedDate.value = value
}

const selectedKey = computed(() => formatCalendarDate(selectedDate.value))
const eventsForSelected = computed(() =>
  events.value
    .filter((e) => e.date === selectedKey.value)
    .sort((a, b) => a.start.localeCompare(b.start)),
)

const todayCount = computed(() => events.value.filter((e) => e.date === formatCalendarDate(new Date())).length)
const monthCount = computed(() => {
  const ym = selectedKey.value.slice(0, 7)
  return events.value.filter((e) => e.date.startsWith(ym)).length
})

const upcoming = computed(() =>
  events.value
    .map((e) => ({ ...e, ts: new Date(`${e.date}T${e.start}:00`).getTime() }))
    .sort((a, b) => a.ts - b.ts),
)
const nextEvent = computed(() => upcoming.value.find((e) => e.ts > Date.now()) ?? null)
const countdownTarget = computed(() =>
  nextEvent.value ? new Date(nextEvent.value.ts) : new Date(Date.now() + 45 * 60 * 1000),
)
function handleCountdownFinish() {
  Message.info({ content: '有一个日程已到开始时间（演示）', duration: 2600 })
}

const upcomingList = computed<ListItem[]>(() =>
  upcoming.value
    .filter((e) => e.ts > Date.now())
    .slice(0, 5)
    .map((e) => ({
      key: e.id,
      title: `${e.date} ${e.start} · ${e.title}`,
      description: `${TYPE_META[e.type].label} · ${e.location}`,
    })),
)

const drawerOpen = ref(false)
const form = ref({
  title: '',
  date: new Date('2026-06-29T00:00:00') as DatePickerModelValue,
  start: '10:00' as TimePickerModelValue,
  end: '11:00' as TimePickerModelValue,
  type: 'meeting' as CalendarEventType,
  location: '',
})
function openDrawer() {
  form.value = {
    title: '',
    date: selectedDate.value,
    start: '10:00',
    end: '11:00',
    type: 'meeting',
    location: '',
  }
  drawerOpen.value = true
}
function toDateStr(value: DatePickerModelValue): string {
  if (!value) return selectedKey.value
  const single = Array.isArray(value) ? value[0] : value
  if (!single) return selectedKey.value
  return formatCalendarDate(single instanceof Date ? single : new Date(single))
}
function asTime(value: TimePickerModelValue, fallback: string): string {
  const single = Array.isArray(value) ? value[0] : value
  return typeof single === 'string' && single ? single : fallback
}

async function loadEvents() {
  loading.value = true
  try {
    const range = calendarQueryRange(selectedDate.value)
    const payload = await fetchCalendarEvents(range.from, range.to)
    events.value = payload.data ?? []
  } catch (error: unknown) {
    Message.error({ content: readErrorMessage(error, '日程加载失败'), duration: 3000 })
  } finally {
    loading.value = false
  }
}

async function submitEvent() {
  const title = form.value.title.trim()
  if (!title) {
    Message.warning({ content: '请填写日程标题', duration: 2000 })
    return
  }
  const date = toDateStr(form.value.date)
  submitting.value = true
  try {
    await createCalendarEvent({
      date,
      start: asTime(form.value.start, '10:00'),
      end: asTime(form.value.end, '11:00'),
      title,
      type: form.value.type,
      location: form.value.location.trim() || '—',
    })
    selectedDate.value = new Date(`${date}T00:00:00`)
    drawerOpen.value = false
    Message.success({ content: `日程「${title}」已创建`, duration: 2400 })
    await loadEvents()
  } catch (error: unknown) {
    Message.error({ content: readErrorMessage(error, '创建日程失败'), duration: 3000 })
  } finally {
    submitting.value = false
  }
}

watch(
  () => `${selectedDate.value.getFullYear()}-${selectedDate.value.getMonth()}`,
  () => {
    void loadEvents()
  },
)

onMounted(() => {
  void loadEvents()
})
</script>

<template>
  <div class="space-y-6">
    <PageHeader
      icon="calendar"
      title="团队日历"
      subtitle="查看团队日程、倒计时下一场会议，并快速新建事件"
      :tags="[
        { label: '协作', variant: 'primary' },
        { label: '演示数据', variant: 'info' },
      ]"
    />

    <div class="grid grid-cols-1 gap-4 sm:grid-cols-3">
      <Card>
        <Countdown
          :value="countdownTarget"
          format="DD 天 HH:mm:ss"
          :title="nextEvent ? `距离「${nextEvent.title}」` : '暂无即将到来的日程'"
          size="lg"
          @finish="handleCountdownFinish"
        />
        <Text v-if="nextEvent" size="sm" color="secondary" class="mt-1 block">
          {{ nextEvent.date }} {{ nextEvent.start }} · {{ TYPE_META[nextEvent.type].label }}
        </Text>
      </Card>
      <Card><Statistic title="今日日程" :value="todayCount" suffix="项" /></Card>
      <Card><Statistic title="本月日程" :value="monthCount" suffix="项" /></Card>
    </div>

    <div class="flex items-center justify-end">
      <Button @click="openDrawer">
        <Icon name="plus" :size="16" class="mr-1" />
        新建事件
      </Button>
    </div>

    <div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
      <Card class="lg:col-span-2">
        <template #header><Text weight="bold">日历</Text></template>
        <Calendar
          :model-value="selectedDate"
          mode="month"
          :fullscreen="true"
          @update:model-value="onDateChange"
          @change="onDateChange"
        />
        <MutedPanel
          compact
          class="mt-3"
          description="点击日期查看当天日程；事件按类型在右侧列表中以标记区分。"
        />
      </Card>

      <div class="space-y-6">
        <Card>
          <template #header>
            <div class="flex items-center gap-2">
              <Text weight="bold">{{ selectedKey }} 日程</Text>
              <Badge :content="eventsForSelected.length" variant="primary" standalone />
            </div>
          </template>

          <MutedPanel v-if="loading && events.length === 0" compact description="正在加载日程…" />
          <div v-else-if="eventsForSelected.length" class="space-y-2">
            <Popover
              v-for="e in eventsForSelected"
              :key="e.id"
              trigger="hover"
              placement="left"
              :width="260"
            >
              <template #trigger>
                <div
                  class="flex items-center gap-3 rounded-lg border border-(--tiger-border,#e5e7eb) p-3 transition-colors hover:bg-(--tiger-bg-hover,#f1f5f9)"
                >
                  <Badge type="dot" :variant="TYPE_META[e.type].variant" />
                  <div class="min-w-0 flex-1">
                    <Text weight="medium" class="truncate block">{{ e.title }}</Text>
                    <Text size="sm" color="secondary">{{ e.start }}–{{ e.end }}</Text>
                  </div>
                  <Tag :variant="TYPE_META[e.type].variant" size="sm">
                    {{ TYPE_META[e.type].label }}
                  </Tag>
                </div>
              </template>
              <template #content>
                <div class="space-y-1 p-3 text-sm">
                  <Text weight="bold" class="block">{{ e.title }}</Text>
                  <div>时间：{{ e.date }} {{ e.start }}–{{ e.end }}</div>
                  <div>类型：{{ TYPE_META[e.type].label }}</div>
                  <div>地点：{{ e.location }}</div>
                </div>
              </template>
            </Popover>
          </div>
          <MutedPanel v-else compact description="当天暂无日程，点击“新建事件”添加一条。" />
        </Card>

        <Card>
          <template #header><Text weight="bold">即将到来</Text></template>
          <List v-if="upcomingList.length" :data-source="upcomingList" />
          <MutedPanel v-else compact description="近期没有更多日程安排。" />
        </Card>
      </div>
    </div>

    <!-- 新建事件 -->
    <Drawer
      placement="right"
      :open="drawerOpen"
      title="新建事件"
      width="420px"
      :mask="true"
      :mask-closable="true"
      @update:open="(v: boolean) => (drawerOpen = v)"
      @close="drawerOpen = false"
    >
      <div class="space-y-4">
        <div>
          <Text weight="medium" class="mb-1 block">标题</Text>
          <Input v-model="form.title" placeholder="例如：迭代评审会" />
        </div>
        <div>
          <Text weight="medium" class="mb-1 block">日期</Text>
          <DatePicker v-model="form.date" placeholder="选择日期" />
        </div>
        <div class="grid grid-cols-2 gap-3">
          <div>
            <Text weight="medium" class="mb-1 block">开始</Text>
            <TimePicker v-model="form.start" :show-seconds="false" />
          </div>
          <div>
            <Text weight="medium" class="mb-1 block">结束</Text>
            <TimePicker v-model="form.end" :show-seconds="false" />
          </div>
        </div>
        <div>
          <Text weight="medium" class="mb-1 block">类型</Text>
          <RadioGroup v-model="form.type">
            <Radio value="meeting">会议</Radio>
            <Radio value="review">评审</Radio>
            <Radio value="release">发布</Radio>
            <Radio value="reminder">提醒</Radio>
          </RadioGroup>
        </div>
        <div>
          <Text weight="medium" class="mb-1 block">地点</Text>
          <Input v-model="form.location" placeholder="会议室 / 线上链接（选填）" />
        </div>
        <div class="flex justify-end gap-2 pt-2">
          <Button variant="outline" @click="drawerOpen = false">取消</Button>
          <Button :disabled="submitting" @click="submitEvent">创建事件</Button>
        </div>
      </div>
    </Drawer>
  </div>
</template>

// Tigercat.Admin.React/src/pages/CalendarPage.tsx
import { useEffect, useMemo, useState } from 'react';
import { Card, Text, Tag, Button, Input, Message } from '@expcat/tigercat-react';
import { Calendar } from '@expcat/tigercat-react/Calendar';
import { Countdown } from '@expcat/tigercat-react/Countdown';
import { Statistic } from '@expcat/tigercat-react/Statistic';
import { Badge } from '@expcat/tigercat-react/Badge';
import { Popover } from '@expcat/tigercat-react/Popover';
import { List } from '@expcat/tigercat-react/List';
import { Drawer } from '@expcat/tigercat-react/Drawer';
import { DatePicker } from '@expcat/tigercat-react/DatePicker';
import { TimePicker } from '@expcat/tigercat-react/TimePicker';
import { RadioGroup } from '@expcat/tigercat-react/RadioGroup';
import { Radio } from '@expcat/tigercat-react/Radio';
import type {
  ListItem,
  TagVariant,
  BadgeVariant,
} from '@expcat/tigercat-core';
import { PageHeader } from '../components/PageHeader';
import { MutedPanel } from '../components/PageFragments';
import { CalendarIcon, PlusIcon } from '../components/Icons';
import {
  calendarQueryRange,
  createCalendarEvent,
  fetchCalendarEvents,
  formatCalendarDate,
  type CalendarEvent,
  type CalendarEventType,
} from '../utils/calendar';

const TYPE_META: Record<CalendarEventType, { label: string; variant: TagVariant }> = {
  meeting: { label: '会议', variant: 'primary' },
  review: { label: '评审', variant: 'warning' },
  release: { label: '发布', variant: 'danger' },
  reminder: { label: '提醒', variant: 'info' },
};

const readErrorMessage = (error: unknown, fallback: string) =>
  error instanceof Error && error.message ? error.message : fallback;

function CalendarPage() {
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [selectedDate, setSelectedDate] = useState<Date>(new Date('2026-06-29T00:00:00'));
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [form, setForm] = useState<{
    title: string;
    date: Date | null;
    start: string;
    end: string;
    type: CalendarEventType;
    location: string;
  }>({
    title: '',
    date: new Date('2026-06-29T00:00:00'),
    start: '10:00',
    end: '11:00',
    type: 'meeting',
    location: '',
  });

  const selectedKey = formatCalendarDate(selectedDate);
  const monthKey = `${selectedDate.getFullYear()}-${selectedDate.getMonth()}`;

  useEffect(() => {
    let cancelled = false;
    const loadEvents = async () => {
      setLoading(true);
      try {
        const range = calendarQueryRange(selectedDate);
        const payload = await fetchCalendarEvents(range.from, range.to);
        if (!cancelled) {
          setEvents(payload.data ?? []);
        }
      } catch (error: unknown) {
        if (!cancelled) {
          Message.error({ content: readErrorMessage(error, '日程加载失败'), duration: 3000 });
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };
    void loadEvents();
    return () => {
      cancelled = true;
    };
    // selectedDate is read inside to compute the visible-month range; monthKey is the refetch trigger.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [monthKey]);

  const eventsForSelected = useMemo(
    () =>
      events
        .filter((e) => e.date === selectedKey)
        .sort((a, b) => a.start.localeCompare(b.start)),
    [events, selectedKey],
  );

  const todayCount = useMemo(
    () => events.filter((e) => e.date === formatCalendarDate(new Date())).length,
    [events],
  );
  const monthCount = useMemo(() => {
    const ym = selectedKey.slice(0, 7);
    return events.filter((e) => e.date.startsWith(ym)).length;
  }, [events, selectedKey]);

  const upcoming = useMemo(
    () =>
      events
        .map((e) => ({ ...e, ts: new Date(`${e.date}T${e.start}:00`).getTime() }))
        .sort((a, b) => a.ts - b.ts),
    [events],
  );
  const nextEvent = useMemo(() => upcoming.find((e) => e.ts > Date.now()) ?? null, [upcoming]);
  const countdownTarget = nextEvent ? new Date(nextEvent.ts) : new Date(Date.now() + 45 * 60 * 1000);

  const upcomingList: ListItem[] = useMemo(
    () =>
      upcoming
        .filter((e) => e.ts > Date.now())
        .slice(0, 5)
        .map((e) => ({
          key: e.id,
          title: `${e.date} ${e.start} · ${e.title}`,
          description: `${TYPE_META[e.type].label} · ${e.location}`,
        })),
    [upcoming],
  );

  const openDrawer = () => {
    setForm({
      title: '',
      date: selectedDate,
      start: '10:00',
      end: '11:00',
      type: 'meeting',
      location: '',
    });
    setDrawerOpen(true);
  };

  const toDateStr = (value: Date | null): string => {
    if (!value) return selectedKey;
    return formatCalendarDate(value);
  };
  const asTime = (value: string, fallback: string): string =>
    value ? value : fallback;

  const submitEvent = async () => {
    const title = form.title.trim();
    if (!title) {
      Message.warning({ content: '请填写日程标题', duration: 2000 });
      return;
    }
    const date = toDateStr(form.date);
    setSubmitting(true);
    try {
      await createCalendarEvent({
        date,
        start: asTime(form.start, '10:00'),
        end: asTime(form.end, '11:00'),
        title,
        type: form.type,
        location: form.location.trim() || '—',
      });
      setSelectedDate(new Date(`${date}T00:00:00`));
      setDrawerOpen(false);
      Message.success({ content: `日程「${title}」已创建`, duration: 2400 });
      const range = calendarQueryRange(new Date(`${date}T00:00:00`));
      const payload = await fetchCalendarEvents(range.from, range.to);
      setEvents(payload.data ?? []);
    } catch (error: unknown) {
      Message.error({ content: readErrorMessage(error, '创建日程失败'), duration: 3000 });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader
        icon={<CalendarIcon size={24} />}
        title="团队日历"
        subtitle="查看团队日程、倒计时下一场会议，并快速新建事件"
        tags={[
          { label: '协作', variant: 'primary' },
          { label: '演示数据', variant: 'info' },
        ]}
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <Card>
          <Countdown
            value={countdownTarget}
            format="DD 天 HH:mm:ss"
            title={nextEvent ? `距离「${nextEvent.title}」` : '暂无即将到来的日程'}
            size="lg"
            onFinish={() => Message.info({ content: '有一个日程已到开始时间（演示）', duration: 2600 })}
          />
          {nextEvent && (
            <Text size="sm" color="secondary" className="mt-1 block">
              {nextEvent.date} {nextEvent.start} · {TYPE_META[nextEvent.type].label}
            </Text>
          )}
        </Card>
        <Card>
          <Statistic title="今日日程" value={todayCount} suffix="项" />
        </Card>
        <Card>
          <Statistic title="本月日程" value={monthCount} suffix="项" />
        </Card>
      </div>

      <div className="flex items-center justify-end">
        <Button onClick={openDrawer}>
          <span className="mr-1 inline-flex align-middle">
            <PlusIcon size={16} />
          </span>
          新建事件
        </Button>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <Card header={<Text weight="bold">日历</Text>} className="lg:col-span-2">
          <Calendar value={selectedDate} mode="month" fullscreen onChange={(d) => setSelectedDate(d)} />
          <MutedPanel
            compact
            className="mt-3"
            description="点击日期查看当天日程；事件按类型在右侧列表中以标记区分。"
          />
        </Card>

        <div className="space-y-6">
          <Card
            header={
              <div className="flex items-center gap-2">
                <Text weight="bold">{selectedKey} 日程</Text>
                <Badge content={eventsForSelected.length} variant="primary" standalone />
              </div>
            }>
            {loading && events.length === 0 ? (
              <MutedPanel compact description="正在加载日程…" />
            ) : eventsForSelected.length ? (
              <div className="space-y-2">
                {eventsForSelected.map((e) => (
                  <Popover
                    key={e.id}
                    trigger="hover"
                    placement="left"
                    width={260}
                    contentContent={
                      <div className="space-y-1 p-3 text-sm">
                        <Text weight="bold" className="block">
                          {e.title}
                        </Text>
                        <div>
                          时间：{e.date} {e.start}–{e.end}
                        </div>
                        <div>类型：{TYPE_META[e.type].label}</div>
                        <div>地点：{e.location}</div>
                      </div>
                    }>
                    <div className="flex items-center gap-3 rounded-lg border border-(--tiger-border,#e5e7eb) p-3 transition-colors hover:bg-(--tiger-bg-hover,#f1f5f9)">
                      <Badge type="dot" variant={TYPE_META[e.type].variant as BadgeVariant} />
                      <div className="min-w-0 flex-1">
                        <Text weight="medium" className="block truncate">
                          {e.title}
                        </Text>
                        <Text size="sm" color="secondary">
                          {e.start}–{e.end}
                        </Text>
                      </div>
                      <Tag variant={TYPE_META[e.type].variant} size="sm">
                        {TYPE_META[e.type].label}
                      </Tag>
                    </div>
                  </Popover>
                ))}
              </div>
            ) : (
              <MutedPanel compact description="当天暂无日程，点击“新建事件”添加一条。" />
            )}
          </Card>

          <Card header={<Text weight="bold">即将到来</Text>}>
            {upcomingList.length ? (
              <List dataSource={upcomingList} />
            ) : (
              <MutedPanel compact description="近期没有更多日程安排。" />
            )}
          </Card>
        </div>
      </div>

      {/* 新建事件 */}
      <Drawer
        placement="right"
        open={drawerOpen}
        title="新建事件"
        width="420px"
        mask
        maskClosable
        onClose={() => setDrawerOpen(false)}>
        <div className="space-y-4">
          <div>
            <Text weight="medium" className="mb-1 block">
              标题
            </Text>
            <Input value={form.title} onChange={(e) => setForm((s) => ({ ...s, title: e.target.value }))} placeholder="例如：迭代评审会" />
          </div>
          <div>
            <Text weight="medium" className="mb-1 block">
              日期
            </Text>
            <DatePicker value={form.date} onChange={(d) => setForm((s) => ({ ...s, date: d }))} placeholder="选择日期" />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Text weight="medium" className="mb-1 block">
                开始
              </Text>
              <TimePicker value={form.start} onChange={(t) => setForm((s) => ({ ...s, start: t ?? '10:00' }))} showSeconds={false} />
            </div>
            <div>
              <Text weight="medium" className="mb-1 block">
                结束
              </Text>
              <TimePicker value={form.end} onChange={(t) => setForm((s) => ({ ...s, end: t ?? '11:00' }))} showSeconds={false} />
            </div>
          </div>
          <div>
            <Text weight="medium" className="mb-1 block">
              类型
            </Text>
            <RadioGroup value={form.type} onChange={(value) => setForm((s) => ({ ...s, type: value as CalendarEventType }))}>
              <Radio value="meeting">会议</Radio>
              <Radio value="review">评审</Radio>
              <Radio value="release">发布</Radio>
              <Radio value="reminder">提醒</Radio>
            </RadioGroup>
          </div>
          <div>
            <Text weight="medium" className="mb-1 block">
              地点
            </Text>
            <Input value={form.location} onChange={(e) => setForm((s) => ({ ...s, location: e.target.value }))} placeholder="会议室 / 线上链接（选填）" />
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <Button variant="outline" onClick={() => setDrawerOpen(false)}>
              取消
            </Button>
            <Button disabled={submitting} onClick={() => void submitEvent()}>
              创建事件
            </Button>
          </div>
        </div>
      </Drawer>
    </div>
  );
}

export default CalendarPage;
