// Tigercat.Admin.Vue/src/pages/ProfilePage.vue
<script setup lang="ts">
import { reactive, ref, inject, computed, onMounted } from 'vue'
import { Avatar } from '@expcat/tigercat-vue/Avatar'
import { Button } from '@expcat/tigercat-vue/Button'
import { Card } from '@expcat/tigercat-vue/Card'
import { Message } from '@expcat/tigercat-vue/Message'
import { Switch } from '@expcat/tigercat-vue/Switch'
import { Tag } from '@expcat/tigercat-vue/Tag'
import { Text } from '@expcat/tigercat-vue/Text'
import { Tabs } from '@expcat/tigercat-vue/Tabs'
import { TabPane } from '@expcat/tigercat-vue/TabPane'
import { Descriptions } from '@expcat/tigercat-vue/Descriptions'
import { Statistic } from '@expcat/tigercat-vue/Statistic'
import { Rate } from '@expcat/tigercat-vue/Rate'
import { QRCode } from '@expcat/tigercat-vue/QRCode'
import { Signature } from '@expcat/tigercat-vue/Signature'
import { ColorSwatch } from '@expcat/tigercat-vue/ColorSwatch'
import { Timeline } from '@expcat/tigercat-vue/Timeline'
import { List } from '@expcat/tigercat-vue/List'
import { Badge } from '@expcat/tigercat-vue/Badge'
import { Divider } from '@expcat/tigercat-vue/Divider'
import { Space } from '@expcat/tigercat-vue/Space'
import { Radio } from '@expcat/tigercat-vue/Radio'
import { RadioGroup } from '@expcat/tigercat-vue/RadioGroup'
import { Textarea } from '@expcat/tigercat-vue/Textarea'
import { Slider } from '@expcat/tigercat-vue/Slider'
import { DatePicker } from '@expcat/tigercat-vue/DatePicker'
import { TimePicker } from '@expcat/tigercat-vue/TimePicker'
import { InputOTP } from '@expcat/tigercat-vue/InputOTP'
import { MaskInput } from '@expcat/tigercat-vue/MaskInput'
import { Row } from '@expcat/tigercat-vue/Row'
import { Col } from '@expcat/tigercat-vue/Col'
import type {
  DescriptionsItem,
  TimelineItem,
  ListItem,
  DatePickerModelValue,
  TimePickerModelValue,
} from '@expcat/tigercat-core'
import {
  DEMO_OTP_CODE,
  OTP_LENGTH,
  PHONE_MASK,
  fetchTwoFactorStatus,
  updateTwoFactorEnabled,
  type Session,
} from '../utils'
import PageHeader from '../components/PageHeader.vue'
import MutedPanel from '../components/MutedPanel.vue'

const session = inject<import('vue').Ref<Session | null>>('session', ref(null))

const activeTab = ref<string | number>('basic')

const username = computed(() => session?.value?.username ?? 'Admin')
const avatarInitial = computed(() => username.value.charAt(0).toUpperCase())

const profile = reactive({
  email: 'admin@tigercat.dev',
  role: '超级管理员',
  department: '平台研发部',
  registeredAt: '2025-08-12',
  lastLoginAt: '2026-06-29 09:12',
})

const basicItems = computed<DescriptionsItem[]>(() => [
  { label: '用户名', content: username.value },
  { label: '邮箱', content: profile.email },
  { label: '角色', content: profile.role },
  { label: '部门', content: profile.department },
  { label: '注册时间', content: profile.registeredAt },
  { label: '最近登录', content: profile.lastLoginAt },
])

const accountLevel = ref(4)

// 安全设置
const security = reactive({
  twoFactor: false,
  loginAlert: true,
  remoteProtect: false,
})
const signature = ref('')
const phone = ref('13800138000')
const bindCode = ref('')
const twoFactorPending = ref(false)
const twoFactorLoading = ref(false)
const totpUri =
  'otpauth://totp/TigercatAdmin:admin?secret=JBSWY3DPEHPK3PXP&issuer=Tigercat'

async function loadTwoFactor() {
  try {
    const payload = await fetchTwoFactorStatus()
    security.twoFactor = Boolean(payload.data?.enabled)
  } catch {
    security.twoFactor = false
  }
}

async function handleTwoFactorChange(enabled: boolean) {
  if (enabled) {
    twoFactorPending.value = true
    bindCode.value = ''
    return
  }
  twoFactorPending.value = false
  bindCode.value = ''
  twoFactorLoading.value = true
  try {
    const payload = await updateTwoFactorEnabled(false)
    security.twoFactor = Boolean(payload.data?.enabled)
    Message.success({ content: '两步验证已关闭', duration: 2000 })
  } catch (error: any) {
    Message.error({ content: error.message, duration: 3000 })
  } finally {
    twoFactorLoading.value = false
  }
}

async function confirmTwoFactorBind() {
  if (bindCode.value !== DEMO_OTP_CODE) {
    Message.error({ content: '验证码错误', duration: 2000 })
    return
  }
  twoFactorLoading.value = true
  try {
    const payload = await updateTwoFactorEnabled(true)
    security.twoFactor = Boolean(payload.data?.enabled)
    twoFactorPending.value = false
    bindCode.value = ''
    Message.success({ content: '两步验证已开启', duration: 2000 })
  } catch (error: any) {
    Message.error({ content: error.message, duration: 3000 })
  } finally {
    twoFactorLoading.value = false
  }
}

onMounted(() => {
  void loadTwoFactor()
})

// 偏好
const density = ref<string>('comfortable')
const themeColor = ref<string>('#3b82f6')
const fontSize = ref<number>(14)
const birthday = ref<DatePickerModelValue>(null)
const quietHours = ref<TimePickerModelValue>(['22:00', '07:00'])
const bio = ref('负责 Tigercat 后台平台的整体架构与组件治理。')
const emailDigest = ref(true)
const swatchColors = ['#3b82f6', '#22c55e', '#a855f7', '#ef4444', '#f97316', '#14b8a6']
const fontMarks: Record<number, string> = { 12: '小', 16: '中', 20: '大' }

// 登录设备
const devices = ref<ListItem[]>([
  { key: 'd1', title: 'MacBook Pro · Chrome', description: '上海 · 当前设备 · 192.168.1.20' },
  { key: 'd2', title: 'iPhone 15 · Safari', description: '上海 · 移动网络 · 10 分钟前活跃' },
  { key: 'd3', title: 'Windows · Edge', description: '北京 · 3 天前活跃' },
])
const loginHistory = ref<TimelineItem[]>([
  { key: 'h1', label: '2026-06-29 09:12', content: '登录成功 · MacBook Pro · Chrome', color: '#22c55e' },
  { key: 'h2', label: '2026-06-28 18:40', content: '退出登录 · MacBook Pro', color: '#64748b' },
  { key: 'h3', label: '2026-06-26 08:05', content: '登录成功 · iPhone 15 · Safari', color: '#22c55e' },
  { key: 'h4', label: '2026-06-22 21:30', content: '异地登录提醒 · 北京 · Edge', color: '#f97316' },
])

function handleTabChange(key: string | number) {
  activeTab.value = key
}
function handleDensityChange(value: string | number) {
  density.value = String(value)
}
function handleFontSizeChange(value: number | [number, number]) {
  fontSize.value = typeof value === 'number' ? value : value[0]
}
function handleBirthdayChange(value: unknown) {
  birthday.value = value as DatePickerModelValue
}
function handleQuietHoursChange(value: TimePickerModelValue) {
  quietHours.value = value
}
function handleSave(scope: string) {
  Message.success({ content: `${scope}已保存（演示）`, duration: 2400 })
}
</script>

<template>
  <div class="space-y-6">
    <PageHeader
      icon="user"
      title="个人中心"
      subtitle="管理你的资料、安全选项、偏好与登录设备"
      :tags="[
        { label: '已认证', variant: 'success' },
        { label: '管理员', variant: 'primary' },
      ]"
    />

    <Tabs :active-key="activeTab" @update:active-key="handleTabChange">
      <!-- 基本资料 -->
      <TabPane tab-key="basic" label="基本资料">
        <div class="space-y-6">
          <Card>
            <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div class="flex items-center gap-4">
                <Badge type="dot" variant="success" :standalone="false">
                  <Avatar
                    size="xl"
                    class="font-bold bg-gradient-to-tr from-(--tiger-primary,#3b82f6) to-blue-400 text-white"
                  >
                    {{ avatarInitial }}
                  </Avatar>
                </Badge>
                <div class="min-w-0">
                  <Text size="lg" weight="bold" class="p2-text-primary">{{ username }}</Text>
                  <div class="mt-1 flex items-center gap-2">
                    <Tag variant="primary" size="sm">{{ profile.role }}</Tag>
                    <Text size="sm" color="secondary">{{ profile.department }}</Text>
                  </div>
                </div>
              </div>
              <div class="flex items-center gap-2">
                <Text size="sm" color="secondary">账号活跃度</Text>
                <Rate :model-value="accountLevel" disabled allow-half />
              </div>
            </div>
          </Card>

          <Row :gutter="[16, 16]">
            <Col :span="{ xs: 24, sm: 8 }">
              <Card><Statistic title="登录次数" :value="1280" group-separator /></Card>
            </Col>
            <Col :span="{ xs: 24, sm: 8 }">
              <Card><Statistic title="积分" :value="4860" suffix="分" /></Card>
            </Col>
            <Col :span="{ xs: 24, sm: 8 }">
              <Card><Statistic title="连续在线" :value="36" suffix="天" /></Card>
            </Col>
          </Row>

          <Card title="资料详情">
            <Descriptions :items="basicItems" :column="{ xs: 1, sm: 2, lg: 3 }" bordered colon />
          </Card>
        </div>
      </TabPane>

      <!-- 安全设置 -->
      <TabPane tab-key="security" label="安全设置">
        <div class="space-y-6">
          <Card title="安全选项">
            <div class="space-y-1">
              <div class="flex items-center justify-between gap-4 py-2">
                <div class="min-w-0">
                  <Text weight="medium">两步验证</Text>
                  <Text size="sm" color="secondary" class="block">登录时额外校验身份验证器动态码</Text>
                </div>
                <Switch
                  :model-value="security.twoFactor || twoFactorPending"
                  :disabled="twoFactorLoading"
                  @update:model-value="handleTwoFactorChange"
                />
              </div>
              <Divider spacing="sm" />
              <div class="flex items-center justify-between gap-4 py-2">
                <div class="min-w-0">
                  <Text weight="medium">登录提醒</Text>
                  <Text size="sm" color="secondary" class="block">新设备登录时发送邮件通知</Text>
                </div>
                <Switch v-model="security.loginAlert" />
              </div>
              <Divider spacing="sm" />
              <div class="flex items-center justify-between gap-4 py-2">
                <div class="min-w-0">
                  <Text weight="medium">异地登录保护</Text>
                  <Text size="sm" color="secondary" class="block">非常用地登录时需二次确认</Text>
                </div>
                <Switch v-model="security.remoteProtect" />
              </div>
            </div>
          </Card>

          <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <Card title="两步验证绑定">
              <div class="flex flex-col items-center gap-3">
                <QRCode :value="totpUri" :size="160" />
                <MutedPanel description="演示环境验证码固定 123456，确认后写入账号 2FA 状态。" />
                <div data-testid="profile-2fa-otp">
                  <InputOTP
                    v-model="bindCode"
                    :length="OTP_LENGTH"
                    type="numeric"
                    aria-label="两步验证绑定码"
                  />
                </div>
                <Button
                  :loading="twoFactorLoading"
                  :disabled="bindCode.length !== OTP_LENGTH"
                  @click="confirmTwoFactorBind"
                >
                  确认绑定
                </Button>
              </div>
            </Card>
            <Card title="手机号">
              <MaskInput v-model="phone" :mask="PHONE_MASK" placeholder="请输入手机号" />
              <Text size="sm" color="secondary" class="mt-2 block">仅用于演示掩码输入，本期不持久化。</Text>
            </Card>

            <Card title="电子签名">
              <Signature v-model="signature" :height="160" clearable clear-text="清除" />
              <Space class="mt-3">
                <Button variant="outline" @click="signature = ''">清除</Button>
                <Button @click="handleSave('电子签名')">保存签名</Button>
              </Space>
            </Card>
          </div>
        </div>
      </TabPane>

      <!-- 偏好 -->
      <TabPane tab-key="preference" label="偏好">
        <Card title="界面与通知偏好">
          <div class="space-y-6">
            <div>
              <Text weight="medium" class="mb-2 block">界面密度</Text>
              <RadioGroup :value="density" @update:value="handleDensityChange">
                <Space>
                  <Radio :value="'compact'">紧凑</Radio>
                  <Radio :value="'comfortable'">适中</Radio>
                  <Radio :value="'loose'">宽松</Radio>
                </Space>
              </RadioGroup>
            </div>

            <div>
              <Text weight="medium" class="mb-2 block">主题色</Text>
              <ColorSwatch v-model="themeColor" :colors="swatchColors" :columns="6" />
            </div>

            <div>
              <Text weight="medium" class="mb-2 block">界面字号</Text>
              <div class="max-w-sm">
                <Slider
                  :value="fontSize"
                  @update:value="handleFontSizeChange"
                  :min="12"
                  :max="20"
                  :step="1"
                  :marks="fontMarks"
                  tooltip
                />
              </div>
            </div>

            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div>
                <Text weight="medium" class="mb-2 block">生日</Text>
                <DatePicker
                  :model-value="birthday"
                  @update:model-value="handleBirthdayChange"
                  placeholder="选择生日"
                  clearable
                />
              </div>
              <div>
                <Text weight="medium" class="mb-2 block">免打扰时段</Text>
                <TimePicker
                  :model-value="quietHours"
                  @update:model-value="handleQuietHoursChange"
                  range
                  :show-seconds="false"
                />
              </div>
            </div>

            <div>
              <Text weight="medium" class="mb-2 block">个人简介</Text>
              <Textarea v-model="bio" :rows="4" :max-length="200" show-count placeholder="介绍一下你自己" />
            </div>

            <div class="flex items-center justify-between gap-4">
              <div class="min-w-0">
                <Text weight="medium">邮件摘要</Text>
                <Text size="sm" color="secondary" class="block">每周发送一次工作摘要邮件</Text>
              </div>
              <Switch v-model="emailDigest" />
            </div>

            <div class="flex justify-end">
              <Button @click="handleSave('偏好设置')">保存偏好</Button>
            </div>
          </div>
        </Card>
      </TabPane>

      <!-- 登录设备 -->
      <TabPane tab-key="devices" label="登录设备">
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
          <Card>
            <template #header>
              <div class="flex items-center gap-2">
                <Text weight="bold">当前登录设备</Text>
                <Badge :content="devices.length" variant="primary" standalone />
              </div>
            </template>
            <List :data-source="devices" bordered />
          </Card>

          <Card title="登录历史">
            <Timeline :items="loginHistory" />
          </Card>
        </div>
      </TabPane>
    </Tabs>
  </div>
</template>

// Tigercat.Admin.React/src/pages/ProfilePage.tsx
import { useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { Avatar } from '@expcat/tigercat-react/Avatar';
import { Button } from '@expcat/tigercat-react/Button';
import { Card } from '@expcat/tigercat-react/Card';
import { Message } from '@expcat/tigercat-react/Message';
import { Switch } from '@expcat/tigercat-react/Switch';
import { Tag } from '@expcat/tigercat-react/Tag';
import { Text } from '@expcat/tigercat-react/Text';
import { Tabs } from '@expcat/tigercat-react/Tabs';
import { TabPane } from '@expcat/tigercat-react/TabPane';
import { Descriptions } from '@expcat/tigercat-react/Descriptions';
import { Statistic } from '@expcat/tigercat-react/Statistic';
import { Rate } from '@expcat/tigercat-react/Rate';
import { QRCode } from '@expcat/tigercat-react/QRCode';
import { Signature } from '@expcat/tigercat-react/Signature';
import { ColorSwatch } from '@expcat/tigercat-react/ColorSwatch';
import { Timeline } from '@expcat/tigercat-react/Timeline';
import { List } from '@expcat/tigercat-react/List';
import { Badge } from '@expcat/tigercat-react/Badge';
import { Divider } from '@expcat/tigercat-react/Divider';
import { Space } from '@expcat/tigercat-react/Space';
import { Radio } from '@expcat/tigercat-react/Radio';
import { RadioGroup } from '@expcat/tigercat-react/RadioGroup';
import { Textarea } from '@expcat/tigercat-react/Textarea';
import { Slider } from '@expcat/tigercat-react/Slider';
import { DatePicker } from '@expcat/tigercat-react/DatePicker';
import { TimePicker } from '@expcat/tigercat-react/TimePicker';
import { InputOTP } from '@expcat/tigercat-react/InputOTP';
import { MaskInput } from '@expcat/tigercat-react/MaskInput';
import { Row } from '@expcat/tigercat-react/Row';
import { Col } from '@expcat/tigercat-react/Col';
import { Icon } from '@expcat/tigercat-react/Icon';
import type {
  DescriptionsItem,
  TimelineItem,
  ListItem,
  TimePickerRangeTuple,
} from '@expcat/tigercat-core';
import { PageHeader } from '../components/PageHeader';
import { MutedPanel } from '../components/PageFragments';

import {
  DEMO_OTP_CODE,
  OTP_LENGTH,
  PHONE_MASK,
  fetchTwoFactorStatus,
  updateTwoFactorEnabled,
} from '../utils';

const swatchColors = ['#3b82f6', '#22c55e', '#a855f7', '#ef4444', '#f97316', '#14b8a6'];
const fontMarks: Record<number, string> = { 12: '小', 16: '中', 20: '大' };
const totpUri =
  'otpauth://totp/TigercatAdmin:admin?secret=JBSWY3DPEHPK3PXP&issuer=Tigercat';

const devices: ListItem[] = [
  { key: 'd1', title: 'MacBook Pro · Chrome', description: '上海 · 当前设备 · 192.168.1.20' },
  { key: 'd2', title: 'iPhone 15 · Safari', description: '上海 · 移动网络 · 10 分钟前活跃' },
  { key: 'd3', title: 'Windows · Edge', description: '北京 · 3 天前活跃' },
];

const loginHistory: TimelineItem[] = [
  { key: 'h1', label: '2026-06-29 09:12', content: '登录成功 · MacBook Pro · Chrome', color: '#22c55e' },
  { key: 'h2', label: '2026-06-28 18:40', content: '退出登录 · MacBook Pro', color: '#64748b' },
  { key: 'h3', label: '2026-06-26 08:05', content: '登录成功 · iPhone 15 · Safari', color: '#22c55e' },
  { key: 'h4', label: '2026-06-22 21:30', content: '异地登录提醒 · 北京 · Edge', color: '#f97316' },
];

function ProfilePage() {
  const { username: rawName } = useOutletContext<{ username?: string }>();
  const username = rawName ?? 'Admin';
  const avatarInitial = username.charAt(0).toUpperCase();

  const profile = {
    email: 'admin@tigercat.dev',
    role: '超级管理员',
    department: '平台研发部',
    registeredAt: '2025-08-12',
    lastLoginAt: '2026-06-29 09:12',
  };

  const basicItems: DescriptionsItem[] = [
    { label: '用户名', content: username },
    { label: '邮箱', content: profile.email },
    { label: '角色', content: profile.role },
    { label: '部门', content: profile.department },
    { label: '注册时间', content: profile.registeredAt },
    { label: '最近登录', content: profile.lastLoginAt },
  ];

  // 安全设置
  const [security, setSecurity] = useState({
    twoFactor: false,
    loginAlert: true,
    remoteProtect: false,
  });
  const [phone, setPhone] = useState('13800138000');
  const [bindCode, setBindCode] = useState('');
  const [twoFactorPending, setTwoFactorPending] = useState(false);
  const [twoFactorLoading, setTwoFactorLoading] = useState(false);

  const loadTwoFactor = async () => {
    try {
      const payload = await fetchTwoFactorStatus();
      setSecurity((s) => ({ ...s, twoFactor: Boolean(payload.data?.enabled) }));
    } catch {
      setSecurity((s) => ({ ...s, twoFactor: false }));
    }
  };

  useEffect(() => {
    void loadTwoFactor();
  }, []);

  const handleTwoFactorChange = async (enabled: boolean) => {
    if (enabled) {
      setTwoFactorPending(true);
      setBindCode('');
      return;
    }
    setTwoFactorPending(false);
    setBindCode('');
    setTwoFactorLoading(true);
    try {
      const payload = await updateTwoFactorEnabled(false);
      setSecurity((s) => ({ ...s, twoFactor: Boolean(payload.data?.enabled) }));
      Message.success({ content: '两步验证已关闭', duration: 2000 });
    } catch (error: any) {
      Message.error({ content: error.message, duration: 3000 });
    } finally {
      setTwoFactorLoading(false);
    }
  };

  const confirmTwoFactorBind = async () => {
    if (bindCode !== DEMO_OTP_CODE) {
      Message.error({ content: '验证码错误', duration: 2000 });
      return;
    }
    setTwoFactorLoading(true);
    try {
      const payload = await updateTwoFactorEnabled(true);
      setSecurity((s) => ({ ...s, twoFactor: Boolean(payload.data?.enabled) }));
      setTwoFactorPending(false);
      setBindCode('');
      Message.success({ content: '两步验证已开启', duration: 2000 });
    } catch (error: any) {
      Message.error({ content: error.message, duration: 3000 });
    } finally {
      setTwoFactorLoading(false);
    }
  };

  // 偏好
  const [density, setDensity] = useState<string | number>('comfortable');
  const [themeColor, setThemeColor] = useState('#3b82f6');
  const [fontSize, setFontSize] = useState(14);
  const [birthday, setBirthday] = useState<Date | null>(null);
  const [quietHours, setQuietHours] = useState<TimePickerRangeTuple | null>(['22:00', '07:00']);
  const [bio, setBio] = useState('负责 Tigercat 后台平台的整体架构与组件治理。');
  const [emailDigest, setEmailDigest] = useState(true);

  const handleSave = (scope: string) => {
    Message.success({ content: `${scope}已保存（演示）`, duration: 2400 });
  };

  return (
    <div className="space-y-6">
      <PageHeader
        icon={<Icon name="user" size="lg" />}
        title="个人中心"
        subtitle="管理你的资料、安全选项、偏好与登录设备"
        tags={[
          { label: '已认证', variant: 'success' },
          { label: '管理员', variant: 'primary' },
        ]}
      />

      <Tabs defaultActiveKey="basic">
        {/* 基本资料 */}
        <TabPane tabKey="basic" label="基本资料">
          <div className="space-y-6">
            <Card>
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-center gap-4">
                  <Badge type="dot" variant="success" standalone={false}>
                    <Avatar
                      size="xl"
                      className="font-bold bg-gradient-to-tr from-(--tiger-primary,#3b82f6) to-blue-400 text-white">
                      {avatarInitial}
                    </Avatar>
                  </Badge>
                  <div className="min-w-0">
                    <Text size="lg" weight="bold" className="p2-text-primary">
                      {username}
                    </Text>
                    <div className="mt-1 flex items-center gap-2">
                      <Tag variant="primary" size="sm">
                        {profile.role}
                      </Tag>
                      <Text size="sm" color="secondary">
                        {profile.department}
                      </Text>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Text size="sm" color="secondary">
                    账号活跃度
                  </Text>
                  <Rate value={4} disabled allowHalf />
                </div>
              </div>
            </Card>

            <Row gutter={[16, 16]}>
              <Col span={{ xs: 24, sm: 8 }}>
                <Card>
                  <Statistic title="登录次数" value={1280} groupSeparator />
                </Card>
              </Col>
              <Col span={{ xs: 24, sm: 8 }}>
                <Card>
                  <Statistic title="积分" value={4860} suffix="分" />
                </Card>
              </Col>
              <Col span={{ xs: 24, sm: 8 }}>
                <Card>
                  <Statistic title="连续在线" value={36} suffix="天" />
                </Card>
              </Col>
            </Row>

            <Card title="资料详情">
              <Descriptions items={basicItems} column={{ xs: 1, sm: 2, lg: 3 }} bordered colon />
            </Card>
          </div>
        </TabPane>

        {/* 安全设置 */}
        <TabPane tabKey="security" label="安全设置">
          <div className="space-y-6">
            <Card title="安全选项">
              <div className="space-y-1">
                <div className="flex items-center justify-between gap-4 py-2">
                  <div className="min-w-0">
                    <Text weight="medium">两步验证</Text>
                    <Text size="sm" color="secondary" className="block">
                      登录时额外校验身份验证器动态码
                    </Text>
                  </div>
                  <Switch
                    checked={security.twoFactor || twoFactorPending}
                    aria-label="两步验证"
                    disabled={twoFactorLoading}
                    onChange={handleTwoFactorChange}
                  />
                </div>
                <Divider spacing="sm" />
                <div className="flex items-center justify-between gap-4 py-2">
                  <div className="min-w-0">
                    <Text weight="medium">登录提醒</Text>
                    <Text size="sm" color="secondary" className="block">
                      新设备登录时发送邮件通知
                    </Text>
                  </div>
                  <Switch
                    checked={security.loginAlert}
                    aria-label="登录提醒"
                    onChange={(v) => setSecurity((s) => ({ ...s, loginAlert: v }))}
                  />
                </div>
                <Divider spacing="sm" />
                <div className="flex items-center justify-between gap-4 py-2">
                  <div className="min-w-0">
                    <Text weight="medium">异地登录保护</Text>
                    <Text size="sm" color="secondary" className="block">
                      非常用地登录时需二次确认
                    </Text>
                  </div>
                  <Switch
                    checked={security.remoteProtect}
                    aria-label="异地登录保护"
                    onChange={(v) => setSecurity((s) => ({ ...s, remoteProtect: v }))}
                  />
                </div>
              </div>
            </Card>

            <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
              <Card title="两步验证绑定">
                <div className="flex flex-col items-center gap-3">
                  <QRCode value={totpUri} size={160} />
                  <MutedPanel description="演示环境验证码固定 123456，确认后写入账号 2FA 状态。" />
                  <div data-testid="profile-2fa-otp">
                    <InputOTP
                      value={bindCode}
                      length={OTP_LENGTH}
                      type="numeric"
                      ariaLabel="两步验证绑定码"
                      onChange={setBindCode}
                    />
                  </div>
                  <Button
                    loading={twoFactorLoading}
                    disabled={bindCode.length !== OTP_LENGTH}
                    onClick={confirmTwoFactorBind}
                  >
                    确认绑定
                  </Button>
                </div>
              </Card>
              <Card title="手机号">
                <MaskInput value={phone} mask={PHONE_MASK} placeholder="请输入手机号" onChange={setPhone} />
                <Text size="sm" color="secondary" className="mt-2 block">
                  仅用于演示掩码输入，本期不持久化。
                </Text>
              </Card>

              <Card title="电子签名">
                <Signature height={160} clearable clearText="清除" />
                <Space className="mt-3">
                  <Button onClick={() => handleSave('电子签名')}>保存签名</Button>
                </Space>
              </Card>
            </div>
          </div>
        </TabPane>

        {/* 偏好 */}
        <TabPane tabKey="preference" label="偏好">
          <Card title="界面与通知偏好">
            <div className="space-y-6">
              <div>
                <Text weight="medium" className="mb-2 block">
                  界面密度
                </Text>
                <RadioGroup value={density} onChange={(v) => setDensity(v)}>
                  <Space>
                    <Radio value="compact">紧凑</Radio>
                    <Radio value="comfortable">适中</Radio>
                    <Radio value="loose">宽松</Radio>
                  </Space>
                </RadioGroup>
              </div>

              <div>
                <Text weight="medium" className="mb-2 block">
                  主题色
                </Text>
                <ColorSwatch value={themeColor} onChange={(v) => setThemeColor(v)} colors={swatchColors} columns={6} />
              </div>

              <div>
                <Text weight="medium" className="mb-2 block">
                  界面字号
                </Text>
                <div className="max-w-sm">
                  <Slider
                    value={fontSize}
                    onChange={(v) => setFontSize(typeof v === 'number' ? v : v[0])}
                    min={12}
                    max={20}
                    step={1}
                    marks={fontMarks}
                    tooltip
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <Text weight="medium" className="mb-2 block">
                    生日
                  </Text>
                  <DatePicker value={birthday} onChange={(d) => setBirthday(d)} placeholder="选择生日" clearable />
                </div>
                <div>
                  <Text weight="medium" className="mb-2 block">
                    免打扰时段
                  </Text>
                  <TimePicker range value={quietHours} onChange={(t) => setQuietHours(t)} showSeconds={false} />
                </div>
              </div>

              <div>
                <Text weight="medium" className="mb-2 block">
                  个人简介
                </Text>
                <Textarea
                  value={bio}
                  onChange={setBio}
                  rows={4}
                  maxLength={200}
                  showCount
                  placeholder="介绍一下你自己"
                />
              </div>

              <div className="flex items-center justify-between gap-4">
                <div className="min-w-0">
                  <Text weight="medium">邮件摘要</Text>
                  <Text size="sm" color="secondary" className="block">
                    每周发送一次工作摘要邮件
                  </Text>
                </div>
                <Switch aria-label="邮件摘要" checked={emailDigest} onChange={(v) => setEmailDigest(v)} />
              </div>

              <div className="flex justify-end">
                <Button onClick={() => handleSave('偏好设置')}>保存偏好</Button>
              </div>
            </div>
          </Card>
        </TabPane>

        {/* 登录设备 */}
        <TabPane tabKey="devices" label="登录设备">
          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <Card
              header={
                <div className="flex items-center gap-2">
                  <Text weight="bold">当前登录设备</Text>
                  <Badge content={devices.length} variant="primary" standalone />
                </div>
              }>
              <List dataSource={devices} bordered />
            </Card>

            <Card title="登录历史">
              <Timeline items={loginHistory} />
            </Card>
          </div>
        </TabPane>
      </Tabs>
    </div>
  );
}

export default ProfilePage;
