// Tigercat.Admin.Vue/src/pages/UsersPage.vue
<script setup lang="ts">
import { ref, computed, inject, onMounted, h, watch } from 'vue'
import { Card, Table, Button, Input, Modal, Form, FormItem, Select, Tag, Message } from '@expcat/tigercat-vue'
import type { TableColumn } from '@expcat/tigercat-core'
import PageHeader from '../components/PageHeader.vue'
import Icon from '../components/Icon.vue'
import { apiRequest, type Session } from '../utils'
import { usePermission } from '../utils/permission'

// ---- Types ----
interface RoleInfo { id: number; name: string }
interface UserItem {
  id: number
  username: string
  displayName: string | null
  status: number
  createdAt: string
  updatedAt: string | null
  roles: RoleInfo[]
}
interface PagedResult { items: UserItem[]; total: number; page: number; pageSize: number }

// ---- Permission ----
const { has: hasPerm } = usePermission()
const canCreate = computed(() => hasPerm('user:create'))
const canEdit = computed(() => hasPerm('user:edit'))
const canDelete = computed(() => hasPerm('user:delete'))

// ---- Session ----
const session = inject<import('vue').Ref<Session | null>>('session')!
const authHeaders = computed(() =>
  session.value?.token ? { Authorization: `Bearer ${session.value.token}` } : {}
)

// ---- State ----
const users = ref<UserItem[]>([])
const loading = ref(false)
const keyword = ref('')
const currentPage = ref(1)
const pageSize = ref(10)
const total = ref(0)
const selectedRowKeys = ref<number[]>([])

// Modal state
const modalVisible = ref(false)
const modalTitle = ref('新增用户')
const editingId = ref<number | null>(null)
const formData = ref({
  username: '',
  password: '',
  displayName: '',
  status: 0,
  roleIds: [] as number[],
})
const submitting = ref(false)

// Delete state
const deleteConfirmVisible = ref(false)
const deletingUser = ref<UserItem | null>(null)
const batchDeleteConfirmVisible = ref(false)

// All roles for select
const allRoles = ref<RoleInfo[]>([])

// ---- API calls ----
async function loadUsers() {
  loading.value = true
  try {
    const params = new URLSearchParams({
      page: String(currentPage.value),
      pageSize: String(pageSize.value),
    })
    if (keyword.value.trim()) {
      params.set('keyword', keyword.value.trim())
    }
    const res = await apiRequest<PagedResult>(`/api/users?${params}`, {
      headers: authHeaders.value,
    })
    users.value = res.data.items
    total.value = res.data.total
  } catch (e: any) {
    Message.error({ content: e.message || '加载用户列表失败', duration: 3000 })
  } finally {
    loading.value = false
  }
}

async function loadRoles() {
  try {
    const res = await apiRequest<{ items: RoleInfo[] }>('/api/roles?pageSize=100', {
      headers: authHeaders.value,
    })
    allRoles.value = res.data.items.map((r: any) => ({ id: r.id, name: r.name }))
  } catch {
    // Roles may not be accessible if user lacks permission
    allRoles.value = []
  }
}

async function handleSubmit() {
  // Validation
  if (!editingId.value) {
    if (!formData.value.username.trim()) {
      Message.error({ content: '请输入用户名', duration: 3000 })
      return
    }
    if (!formData.value.password) {
      Message.error({ content: '请输入密码', duration: 3000 })
      return
    }
    if (formData.value.password.length < 6) {
      Message.error({ content: '密码长度不能少于 6 位', duration: 3000 })
      return
    }
  }

  submitting.value = true
  try {
    if (editingId.value) {
      // Update
      const body: Record<string, any> = {
        displayName: formData.value.displayName || null,
        status: formData.value.status,
        roleIds: formData.value.roleIds,
      }
      if (formData.value.password) {
        body.password = formData.value.password
      }
      await apiRequest(`/api/users/${editingId.value}`, {
        method: 'PUT',
        headers: authHeaders.value,
        body: JSON.stringify(body),
      })
      Message.success({ content: '用户更新成功', duration: 3000 })
    } else {
      // Create
      await apiRequest('/api/users', {
        method: 'POST',
        headers: authHeaders.value,
        body: JSON.stringify({
          username: formData.value.username.trim(),
          password: formData.value.password,
          displayName: formData.value.displayName || null,
          roleIds: formData.value.roleIds,
        }),
      })
      Message.success({ content: '用户创建成功', duration: 3000 })
    }
    modalVisible.value = false
    await loadUsers()
  } catch (e: any) {
    Message.error({ content: e.message || '操作失败', duration: 3000 })
  } finally {
    submitting.value = false
  }
}

async function handleDelete(user: UserItem) {
  deletingUser.value = user
  deleteConfirmVisible.value = true
}

async function confirmDelete() {
  if (!deletingUser.value) return
  try {
    await apiRequest(`/api/users/${deletingUser.value.id}`, {
      method: 'DELETE',
      headers: authHeaders.value,
    })
    Message.success({ content: '删除成功', duration: 3000 })
    deleteConfirmVisible.value = false
    deletingUser.value = null
    selectedRowKeys.value = selectedRowKeys.value.filter(k => k !== deletingUser.value?.id)
    await loadUsers()
  } catch (e: any) {
    Message.error({ content: e.message || '删除失败', duration: 3000 })
  }
}

async function handleBatchDelete() {
  if (selectedRowKeys.value.length === 0) {
    Message.error({ content: '请选择要删除的用户', duration: 3000 })
    return
  }
  batchDeleteConfirmVisible.value = true
}

async function confirmBatchDelete() {
  try {
    await apiRequest('/api/users/batch-delete', {
      method: 'POST',
      headers: authHeaders.value,
      body: JSON.stringify({ ids: selectedRowKeys.value }),
    })
    Message.success({ content: `成功删除 ${selectedRowKeys.value.length} 个用户`, duration: 3000 })
    batchDeleteConfirmVisible.value = false
    selectedRowKeys.value = []
    await loadUsers()
  } catch (e: any) {
    Message.error({ content: e.message || '批量删除失败', duration: 3000 })
  }
}

function openCreateModal() {
  editingId.value = null
  modalTitle.value = '新增用户'
  formData.value = { username: '', password: '', displayName: '', status: 0, roleIds: [] }
  modalVisible.value = true
}

function openEditModal(user: UserItem) {
  editingId.value = user.id
  modalTitle.value = '编辑用户'
  formData.value = {
    username: user.username,
    password: '',
    displayName: user.displayName || '',
    status: user.status,
    roleIds: user.roles.map(r => r.id),
  }
  modalVisible.value = true
}

// ---- Table columns ----
const columns = computed<TableColumn[]>(() => {
  const cols: TableColumn[] = [
    { key: 'id', title: 'ID', width: 70, align: 'center' },
    { key: 'username', title: '用户名', width: 150 },
    { key: 'displayName', title: '显示名', width: 150 },
    {
      key: 'status',
      title: '状态',
      width: 100,
      align: 'center',
      render: (record: any) =>
        h(Tag, {
          color: record.status === 0 ? 'green' : 'red',
          size: 'sm',
        }, () => record.status === 0 ? '正常' : '禁用'),
    },
    {
      key: 'roles',
      title: '角色',
      width: 200,
      render: (record: any) => {
        const roles = record.roles as RoleInfo[]
        if (!roles || roles.length === 0) return h('span', { class: 'text-slate-400 text-sm' }, '无角色')
        return h('div', { class: 'flex flex-wrap gap-1' },
          roles.map(r => h(Tag, { color: 'blue', size: 'sm', key: r.id }, () => r.name))
        )
      },
    },
    {
      key: 'createdAt',
      title: '创建时间',
      width: 180,
      render: (record: any) =>
        h('span', { class: 'text-sm text-slate-600' },
          new Date(record.createdAt).toLocaleString('zh-CN')),
    },
  ]

  // Action column (only if user has edit or delete permission)
  if (canEdit.value || canDelete.value) {
    cols.push({
      key: 'actions',
      title: '操作',
      width: 160,
      align: 'center',
      fixed: 'right',
      render: (record: any) => {
        const buttons: any[] = []
        if (canEdit.value) {
          buttons.push(
            h(Button, {
              size: 'sm',
              variant: 'ghost',
              onClick: () => openEditModal(record as UserItem),
            }, () => '编辑')
          )
        }
        if (canDelete.value) {
          buttons.push(
            h(Button, {
              size: 'sm',
              variant: 'ghost',
              color: 'danger',
              onClick: () => handleDelete(record as UserItem),
            }, () => '删除')
          )
        }
        return h('div', { class: 'flex items-center justify-center gap-1' }, buttons)
      },
    })
  }

  return cols
})

// ---- Pagination ----
const paginationConfig = computed(() => ({
  current: currentPage.value,
  pageSize: pageSize.value,
  total: total.value,
  showSizeChanger: true,
  showTotal: true,
  pageSizeOptions: [10, 20, 50],
}))

function handlePageChange(e: any) {
  if (e.current !== undefined) currentPage.value = e.current
  if (e.pageSize !== undefined) {
    pageSize.value = e.pageSize
    currentPage.value = 1
  }
  loadUsers()
}

function handleSelectionChange(keys: (string | number)[]) {
  selectedRowKeys.value = keys as number[]
}

// ---- Search ----
let searchTimer: ReturnType<typeof setTimeout> | null = null
function handleSearch(val: string) {
  keyword.value = val
  if (searchTimer) clearTimeout(searchTimer)
  searchTimer = setTimeout(() => {
    currentPage.value = 1
    loadUsers()
  }, 300)
}

// Role select options
const roleOptions = computed(() =>
  allRoles.value.map(r => ({ label: r.name, value: r.id }))
)

// Status stats from actual data
const activeCount = computed(() => users.value.filter(u => u.status === 0).length)
const disabledCount = computed(() => users.value.filter(u => u.status === 1).length)

// ---- Lifecycle ----
onMounted(() => {
  loadUsers()
  loadRoles()
})
</script>

<template>
  <div class="space-y-6">
    <PageHeader
      title="用户管理"
      subtitle="管理平台用户账号、角色与权限"
      icon="users"
      :tags="[
        { label: '核心模块', color: 'blue' },
        { label: '运行中', color: 'green' }
      ]"
    />

    <!-- Toolbar -->
    <Card>
      <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div class="flex items-center gap-3 flex-wrap">
          <Input
            :model-value="keyword"
            placeholder="搜索用户名或显示名..."
            @update:model-value="handleSearch"
            class="w-64"
          />
        </div>
        <div class="flex items-center gap-2">
          <Button
            v-permission="'user:delete'"
            v-if="selectedRowKeys.length > 0"
            color="danger"
            variant="outline"
            size="sm"
            @click="handleBatchDelete"
          >
            批量删除 ({{ selectedRowKeys.length }})
          </Button>
          <Button
            v-permission="'user:create'"
            color="primary"
            @click="openCreateModal"
          >
            <span class="flex items-center gap-1">
              <Icon name="userPlus" :size="16" />
              新增用户
            </span>
          </Button>
        </div>
      </div>
    </Card>

    <!-- Users Table -->
    <Card>
      <Table
        :columns="columns"
        :data-source="users as any"
        :loading="loading"
        :pagination="paginationConfig"
        :row-selection="{
          selectedRowKeys: selectedRowKeys,
          type: 'checkbox',
        }"
        row-key="id"
        :hoverable="true"
        :striped="true"
        empty-text="暂无用户数据"
        @page-change="handlePageChange"
        @selection-change="handleSelectionChange"
      />
    </Card>

    <!-- Create / Edit Modal -->
    <Modal
      :visible="modalVisible"
      :title="modalTitle"
      ok-text="确定"
      cancel-text="取消"
      @ok="handleSubmit"
      @cancel="modalVisible = false"
      @close="modalVisible = false"
    >
      <Form :model="formData" :label-width="88">
        <FormItem label="用户名" name="username">
          <Input
            v-model="formData.username"
            placeholder="请输入用户名"
            :disabled="!!editingId"
          />
        </FormItem>
        <FormItem label="密码" name="password">
          <Input
            v-model="formData.password"
            type="password"
            :placeholder="editingId ? '留空则不修改密码' : '请输入密码'"
          />
        </FormItem>
        <FormItem label="显示名称" name="displayName">
          <Input
            v-model="formData.displayName"
            placeholder="请输入显示名称（选填）"
          />
        </FormItem>
        <FormItem v-if="editingId" label="状态" name="status">
          <Select
            v-model="formData.status"
            :options="[
              { label: '正常', value: 0 },
              { label: '禁用', value: 1 },
            ]"
            placeholder="请选择状态"
          />
        </FormItem>
        <FormItem label="角色" name="roleIds">
          <Select
            v-model="formData.roleIds"
            :options="roleOptions"
            placeholder="请选择角色（可多选）"
            multiple
          />
        </FormItem>
      </Form>
    </Modal>

    <!-- Single Delete Confirm -->
    <Modal
      :visible="deleteConfirmVisible"
      title="确认删除"
      ok-text="确认删除"
      cancel-text="取消"
      @ok="confirmDelete"
      @cancel="deleteConfirmVisible = false"
      @close="deleteConfirmVisible = false"
    >
      <p class="text-slate-600">
        确定要删除用户
        <span class="font-semibold text-slate-800">{{ deletingUser?.username }}</span>
        吗？此操作不可撤销。
      </p>
    </Modal>

    <!-- Batch Delete Confirm -->
    <Modal
      :visible="batchDeleteConfirmVisible"
      title="确认批量删除"
      ok-text="确认删除"
      cancel-text="取消"
      @ok="confirmBatchDelete"
      @cancel="batchDeleteConfirmVisible = false"
      @close="batchDeleteConfirmVisible = false"
    >
      <p class="text-slate-600">
        确定要删除选中的
        <span class="font-semibold text-slate-800">{{ selectedRowKeys.length }}</span>
        个用户吗？此操作不可撤销。
      </p>
    </Modal>
  </div>
</template>

// Tigercat.Admin.React/src/pages/UsersPage.tsx
import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import {
  Card,
  Table,
  Button,
  Input,
  Modal,
  Form,
  FormItem,
  Select,
  Tag,
  Message,
} from '@expcat/tigercat-react';
import type { TableColumn } from '@expcat/tigercat-core';
import { PageHeader } from '../components/PageHeader';
import { PermissionGuard } from '../components/PermissionGuard';
import { UsersIcon, UserPlusIcon } from '../components/Icons';
import { apiRequest, normalizeInput, debounce, getAuthHeaders } from '../utils';
import { usePermission } from '../utils/permission';
import type {
  RoleInfo,
  UserItem,
  PagedResult,
  MessageResult,
} from '../utils/types';

type UserFormData = {
  username: string;
  password: string;
  displayName: string;
  status: number;
  roleIds: number[];
};

const INITIAL_FORM: UserFormData = {
  username: '',
  password: '',
  displayName: '',
  status: 0,
  roleIds: [],
};

function UsersPage() {
  const { has: hasPerm } = usePermission();

  // ---- State ----
  const [users, setUsers] = useState<UserItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [keyword, setKeyword] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [total, setTotal] = useState(0);
  const [selectedRowKeys, setSelectedRowKeys] = useState<number[]>([]);

  // Modal state
  const [modalVisible, setModalVisible] = useState(false);
  const [modalTitle, setModalTitle] = useState('新增用户');
  const [editingId, setEditingId] = useState<number | null>(null);
  const [formData, setFormData] = useState<UserFormData>({ ...INITIAL_FORM });

  // Delete state
  const [deleteConfirmVisible, setDeleteConfirmVisible] = useState(false);
  const [deletingUser, setDeletingUser] = useState<UserItem | null>(null);
  const [batchDeleteConfirmVisible, setBatchDeleteConfirmVisible] =
    useState(false);

  // All roles for select
  const [allRoles, setAllRoles] = useState<RoleInfo[]>([]);

  // Ref to track current query state (avoids stale closures)
  const queryRef = useRef({ page: currentPage, pageSize, keyword });

  // ---- Permission checks ----
  const canEdit = hasPerm('user:edit');
  const canDelete = hasPerm('user:delete');

  // ---- API calls ----
  const loadUsers = useCallback(async () => {
    setLoading(true);
    try {
      const { page, pageSize: ps, keyword: kw } = queryRef.current;
      const params = new URLSearchParams({
        page: String(page),
        pageSize: String(ps),
      });
      if (kw.trim()) {
        params.set('keyword', kw.trim());
      }
      const res = await apiRequest<PagedResult<UserItem>>(
        `/api/users?${params}`,
        {
          headers: getAuthHeaders(),
        },
      );
      setUsers(res.data.items);
      setTotal(res.data.total);
    } catch (e: any) {
      Message.error({
        content: e.message || '加载用户列表失败',
        duration: 3000,
      });
    } finally {
      setLoading(false);
    }
  }, []);

  const loadRoles = useCallback(async () => {
    try {
      const res = await apiRequest<{ items: RoleInfo[] }>(
        '/api/roles?pageSize=100',
        { headers: getAuthHeaders() },
      );
      setAllRoles(res.data.items.map((r: any) => ({ id: r.id, name: r.name })));
    } catch {
      setAllRoles([]);
    }
  }, []);

  useEffect(() => {
    loadUsers();
    loadRoles();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ---- Form submit (create / update) ----
  const handleSubmit = async () => {
    if (!modalVisible) return;

    // Validation
    if (!editingId) {
      if (!formData.username.trim()) {
        Message.error({ content: '请输入用户名', duration: 3000 });
        return;
      }
      if (!formData.password) {
        Message.error({ content: '请输入密码', duration: 3000 });
        return;
      }
      if (formData.password.length < 6) {
        Message.error({ content: '密码长度不能少于 6 位', duration: 3000 });
        return;
      }
    }

    try {
      if (editingId) {
        const body: Record<string, any> = {
          displayName: formData.displayName || null,
          status: formData.status,
          roleIds: formData.roleIds,
        };
        if (formData.password) {
          body.password = formData.password;
        }
        await apiRequest(`/api/users/${editingId}`, {
          method: 'PUT',
          headers: getAuthHeaders(),
          body: JSON.stringify(body),
        });
        Message.success({ content: '用户更新成功', duration: 3000 });
      } else {
        await apiRequest('/api/users', {
          method: 'POST',
          headers: getAuthHeaders(),
          body: JSON.stringify({
            username: formData.username.trim(),
            password: formData.password,
            displayName: formData.displayName || null,
            roleIds: formData.roleIds,
          }),
        });
        Message.success({ content: '用户创建成功', duration: 3000 });
      }
      setModalVisible(false);
      loadUsers();
    } catch (e: any) {
      Message.error({ content: e.message || '操作失败', duration: 3000 });
    }
  };

  // ---- Delete ----
  const handleDelete = (user: UserItem) => {
    setDeletingUser(user);
    setDeleteConfirmVisible(true);
  };

  const confirmDelete = async () => {
    if (!deletingUser) return;
    const userId = deletingUser.id;
    try {
      await apiRequest(`/api/users/${userId}`, {
        method: 'DELETE',
        headers: getAuthHeaders(),
      });
      Message.success({ content: '删除成功', duration: 3000 });
      setDeleteConfirmVisible(false);
      setDeletingUser(null);
      setSelectedRowKeys((prev) => prev.filter((k) => k !== userId));
      loadUsers();
    } catch (e: any) {
      Message.error({ content: e.message || '删除失败', duration: 3000 });
    }
  };

  // ---- Batch delete ----
  const handleBatchDelete = () => {
    if (selectedRowKeys.length === 0) {
      Message.error({ content: '请选择要删除的用户', duration: 3000 });
      return;
    }
    setBatchDeleteConfirmVisible(true);
  };

  const confirmBatchDelete = async () => {
    try {
      const res = await apiRequest<MessageResult>('/api/users/batch-delete', {
        method: 'POST',
        headers: getAuthHeaders(),
        body: JSON.stringify({ ids: selectedRowKeys }),
      });
      Message.success({
        content: res.data.message || '批量删除成功',
        duration: 3000,
      });
      setBatchDeleteConfirmVisible(false);
      setSelectedRowKeys([]);
      loadUsers();
    } catch (e: any) {
      Message.error({ content: e.message || '批量删除失败', duration: 3000 });
    }
  };

  // ---- Modal helpers ----
  const openCreateModal = () => {
    setEditingId(null);
    setModalTitle('新增用户');
    setFormData({ ...INITIAL_FORM });
    setModalVisible(true);
  };

  const openEditModal = (user: UserItem) => {
    setEditingId(user.id);
    setModalTitle('编辑用户');
    setFormData({
      username: user.username,
      password: '',
      displayName: user.displayName || '',
      status: user.status,
      roleIds: user.roles.map((r) => r.id),
    });
    setModalVisible(true);
  };

  // ---- Search with debounce ----
  const debouncedLoad = useMemo(
    () =>
      debounce(() => {
        queryRef.current.page = 1;
        setCurrentPage(1);
        loadUsers();
      }, 300),
    [loadUsers],
  );

  const handleSearch = (val: string) => {
    const normalized = normalizeInput(val);
    queryRef.current.keyword = normalized;
    setKeyword(normalized);
    debouncedLoad();
  };

  // ---- Table columns ----
  const columns = useMemo<TableColumn<UserItem>[]>(() => {
    const cols: TableColumn<UserItem>[] = [
      { key: 'id', title: 'ID', width: 70, align: 'center' },
      { key: 'username', title: '用户名', width: 150 },
      { key: 'displayName', title: '显示名', width: 150 },
      {
        key: 'status',
        title: '状态',
        width: 100,
        align: 'center',
        render: (record) => (
          <Tag color={record.status === 0 ? 'green' : 'red'} size="sm">
            {record.status === 0 ? '正常' : '禁用'}
          </Tag>
        ),
      },
      {
        key: 'roles',
        title: '角色',
        width: 200,
        render: (record) => {
          const roles = record.roles;
          if (!roles || roles.length === 0)
            return <span className="text-slate-400 text-sm">无角色</span>;
          return (
            <div className="flex flex-wrap gap-1">
              {roles.map((r) => (
                <Tag key={r.id} color="blue" size="sm">
                  {r.name}
                </Tag>
              ))}
            </div>
          );
        },
      },
      {
        key: 'createdAt',
        title: '创建时间',
        width: 180,
        render: (record) => (
          <span className="text-sm text-slate-600">
            {new Date(record.createdAt).toLocaleString('zh-CN')}
          </span>
        ),
      },
    ];

    if (canEdit || canDelete) {
      cols.push({
        key: 'actions',
        title: '操作',
        width: 160,
        align: 'center',
        fixed: 'right',
        render: (record) => (
          <div className="flex items-center justify-center gap-1">
            {canEdit && (
              <Button
                size="sm"
                variant="ghost"
                onClick={() => openEditModal(record)}>
                编辑
              </Button>
            )}
            {canDelete && (
              <Button
                size="sm"
                variant="ghost"
                color="danger"
                onClick={() => handleDelete(record)}>
                删除
              </Button>
            )}
          </div>
        ),
      });
    }

    return cols;
  }, [canEdit, canDelete]);

  // ---- Pagination ----
  const paginationConfig = useMemo(
    () => ({
      current: currentPage,
      pageSize,
      total,
      showSizeChanger: true,
      showTotal: true,
      pageSizeOptions: [10, 20, 50],
    }),
    [currentPage, pageSize, total],
  );

  const handlePageChange = (page: { current: number; pageSize: number }) => {
    if (page.pageSize !== queryRef.current.pageSize) {
      queryRef.current.pageSize = page.pageSize;
      queryRef.current.page = 1;
      setPageSize(page.pageSize);
      setCurrentPage(1);
    } else {
      queryRef.current.page = page.current;
      setCurrentPage(page.current);
    }
    loadUsers();
  };

  // ---- Selection ----
  const handleSelectionChange = (keys: (string | number)[]) => {
    setSelectedRowKeys(keys as number[]);
  };

  // ---- Role select options ----
  const roleOptions = useMemo(
    () => allRoles.map((r) => ({ label: r.name, value: r.id })),
    [allRoles],
  );

  // ---- Form field helpers ----
  const setField = <K extends keyof UserFormData>(
    field: K,
    value: UserFormData[K],
  ) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="用户管理"
        subtitle="管理平台用户账号、角色与权限"
        icon={<UsersIcon size={24} />}
        tags={[
          { label: '核心模块', color: 'blue' },
          { label: '运行中', color: 'green' },
        ]}
      />

      {/* Toolbar */}
      <Card>
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3 flex-wrap">
            <Input
              value={keyword}
              placeholder="搜索用户名或显示名..."
              onChange={(val) => handleSearch(normalizeInput(val))}
              className="w-64"
            />
          </div>
          <div className="flex items-center gap-2">
            <PermissionGuard code="user:delete">
              {selectedRowKeys.length > 0 && (
                <Button
                  color="danger"
                  variant="outline"
                  size="sm"
                  onClick={handleBatchDelete}>
                  批量删除 ({selectedRowKeys.length})
                </Button>
              )}
            </PermissionGuard>
            <PermissionGuard code="user:create">
              <Button color="primary" onClick={openCreateModal}>
                <span className="flex items-center gap-1">
                  <UserPlusIcon size={16} />
                  新增用户
                </span>
              </Button>
            </PermissionGuard>
          </div>
        </div>
      </Card>

      {/* Users Table */}
      <Card>
        <Table
          columns={columns}
          dataSource={users}
          loading={loading}
          pagination={paginationConfig}
          rowSelection={{
            selectedRowKeys,
          }}
          rowKey="id"
          hoverable
          striped
          emptyText="暂无用户数据"
          onPageChange={handlePageChange}
          onSelectionChange={handleSelectionChange}
        />
      </Card>

      {/* Create / Edit Modal */}
      <Modal
        open={modalVisible}
        title={modalTitle}
        okText="确定"
        cancelText="取消"
        onOk={handleSubmit}
        onCancel={() => setModalVisible(false)}>
        <Form model={formData} labelWidth={88}>
          <FormItem label="用户名" name="username">
            <Input
              value={formData.username}
              placeholder="请输入用户名"
              disabled={!!editingId}
              onChange={(val) => setField('username', normalizeInput(val))}
            />
          </FormItem>
          <FormItem label="密码" name="password">
            <Input
              value={formData.password}
              type="password"
              placeholder={editingId ? '留空则不修改密码' : '请输入密码'}
              onChange={(val) => setField('password', normalizeInput(val))}
            />
          </FormItem>
          <FormItem label="显示名称" name="displayName">
            <Input
              value={formData.displayName}
              placeholder="请输入显示名称（选填）"
              onChange={(val) => setField('displayName', normalizeInput(val))}
            />
          </FormItem>
          {editingId && (
            <FormItem label="状态" name="status">
              <Select
                value={formData.status}
                options={[
                  { label: '正常', value: 0 },
                  { label: '禁用', value: 1 },
                ]}
                placeholder="请选择状态"
                onChange={(val) => setField('status', (val as number) ?? 0)}
              />
            </FormItem>
          )}
          <FormItem label="角色" name="roleIds">
            <Select
              value={formData.roleIds}
              options={roleOptions}
              placeholder="请选择角色（可多选）"
              multiple
              onChange={(val) => setField('roleIds', (val as number[]) ?? [])}
            />
          </FormItem>
        </Form>
      </Modal>

      {/* Single Delete Confirm */}
      <Modal
        open={deleteConfirmVisible}
        title="确认删除"
        okText="确认删除"
        cancelText="取消"
        onOk={confirmDelete}
        onCancel={() => setDeleteConfirmVisible(false)}
        role="alertdialog"
        aria-label={`确认删除用户 ${deletingUser?.username ?? ''}`}>
        <p className="text-slate-600">
          确定要删除用户
          <span className="font-semibold text-slate-800">
            {' '}
            {deletingUser?.username}{' '}
          </span>
          吗？此操作不可撤销。
        </p>
      </Modal>

      {/* Batch Delete Confirm */}
      <Modal
        open={batchDeleteConfirmVisible}
        title="确认批量删除"
        okText="确认删除"
        cancelText="取消"
        onOk={confirmBatchDelete}
        onCancel={() => setBatchDeleteConfirmVisible(false)}
        role="alertdialog"
        aria-label={`确认批量删除 ${selectedRowKeys.length} 个用户`}>
        <p className="text-slate-600">
          确定要删除选中的
          <span className="font-semibold text-slate-800">
            {' '}
            {selectedRowKeys.length}{' '}
          </span>
          个用户吗？此操作不可撤销。
        </p>
      </Modal>
    </div>
  );
}

export default UsersPage;
