// Tigercat.Admin.React/src/App.tsx
import { lazy, Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import { Routes, Route, Navigate, useNavigate, useLocation } from 'react-router-dom';
import {
  Container,
  Modal,
  Form,
  FormItem,
  Input,
} from '@expcat/tigercat-react';
import { MainLayout } from './components/MainLayout';
import { ProtectedRoute } from './components/ProtectedRoute';
import { GuestRoute } from './components/GuestRoute';
import {
  SESSION_KEY,
  safeParse,
  apiRequest,
  normalizeInput,
  Session,
  Notice,
} from './utils';

// Lazy load pages
const LoginPage = lazy(() => import('./pages/LoginPage'));
const RegisterPage = lazy(() => import('./pages/RegisterPage'));
const HomePage = lazy(() => import('./pages/HomePage'));
const UsersPage = lazy(() => import('./pages/UsersPage'));
const RolesPage = lazy(() => import('./pages/RolesPage'));
const SettingsPage = lazy(() => import('./pages/SettingsPage'));

const MENU_ROUTES = {
  home: '/dashboard',
  users: '/users',
  roles: '/roles',
  settings: '/settings',
} as const;

type MenuKey = keyof typeof MENU_ROUTES;

const DEFAULT_MENU: MenuKey = 'home';

const PATH_TO_MENU = Object.fromEntries(
  Object.entries(MENU_ROUTES).map(([key, value]) => [value, key as MenuKey]),
) as Record<string, MenuKey | undefined>;

type ChangePasswordForm = { oldPassword: string; newPassword: string };
type ChangePasswordField = keyof ChangePasswordForm;

// Loading fallback component
function PageLoader() {
  return (
    <div className="flex items-center justify-center h-full min-h-[200px]">
      <div className="text-slate-500">加载中...</div>
    </div>
  );
}

// Guest layout wrapper for login/register pages
function GuestLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-100 via-blue-50 to-indigo-100 p-6 flex items-center justify-center">
      <Container className="w-full max-w-4xl" padding={false}>
        <Suspense fallback={<PageLoader />}>
          {children}
        </Suspense>
      </Container>
    </div>
  );
}

interface ProtectedLayoutProps {
  children: React.ReactNode;
  user: { username: string } | null;
  activeMenu: MenuKey;
  onLogout: () => void;
  onChangePassword: () => void;
  onNavigate: (key: MenuKey) => void;
  changeOpen: boolean;
  changeForm: ChangePasswordForm;
  onChangeField: (field: ChangePasswordField, value: string) => void;
  onChangePasswordSubmit: () => void;
  onCloseChangeModal: () => void;
}

function ProtectedLayout({
  children,
  user,
  activeMenu,
  onLogout,
  onChangePassword,
  onNavigate,
  changeOpen,
  changeForm,
  onChangeField,
  onChangePasswordSubmit,
  onCloseChangeModal,
}: ProtectedLayoutProps) {
  return (
    <MainLayout
      user={user}
      onLogout={onLogout}
      onChangePassword={onChangePassword}
      activeMenu={activeMenu}
      onNavigate={onNavigate}>
      {children}
      <Modal
        open={changeOpen}
        title="修改密码"
        okText="确认修改"
        cancelText="取消"
        onOk={onChangePasswordSubmit}
        onCancel={onCloseChangeModal}>
        <Form model={changeForm} labelWidth={88}>
          <FormItem name="oldPassword" label="旧密码">
            <Input
              value={changeForm.oldPassword}
              placeholder="请输入旧密码"
              onChange={(value) =>
                onChangeField('oldPassword', normalizeInput(value))
              }
            />
          </FormItem>
          <FormItem name="newPassword" label="新密码">
            <Input
              value={changeForm.newPassword}
              placeholder="请输入新密码"
              onChange={(value) =>
                onChangeField('newPassword', normalizeInput(value))
              }
            />
          </FormItem>
        </Form>
      </Modal>
    </MainLayout>
  );
}

function App() {
  const navigate = useNavigate();
  const location = useLocation();

  const [changeForm, setChangeForm] = useState<ChangePasswordForm>({
    oldPassword: '',
    newPassword: '',
  });
  const [session, setSession] = useState<Session | null>(
    () => safeParse<Session>(localStorage.getItem(SESSION_KEY)) || null,
  );
  const [homeMessage, setHomeMessage] = useState('');
  const [notice, setNotice] = useState<Notice>({ type: '', message: '' });
  const [homeError, setHomeError] = useState('');
  const [changeOpen, setChangeOpen] = useState(false);

  const authHeaders = useMemo(() => {
    if (!session?.token) return {};
    return { Authorization: `Bearer ${session.token}` } as HeadersInit;
  }, [session?.token]);

  const persistSession = (nextSession: Session | null) => {
    if (!nextSession) {
      localStorage.removeItem(SESSION_KEY);
    } else {
      localStorage.setItem(SESSION_KEY, JSON.stringify(nextSession));
    }
    setSession(nextSession);
  };

  const onLoginSuccess = async (nextSession: Session) => {
    persistSession(nextSession);
    await loadHome(nextSession.token);
    navigate('/dashboard');
  };

  const loadHome = useCallback(async (tokenOverride?: string) => {
    setHomeError('');
    try {
      const headers = tokenOverride
        ? { Authorization: `Bearer ${tokenOverride}` }
        : authHeaders;
      const payload = await apiRequest<string>('/api/home', {
        headers: headers as HeadersInit,
      });
      setHomeMessage(payload?.data || '');
    } catch (error: any) {
      setHomeError(error.message);
    }
  }, [authHeaders]);

  // Load home data when entering dashboard
  useEffect(() => {
    if (location.pathname === '/dashboard' && session?.token) {
      loadHome(session.token);
    }
  }, [location.pathname, session?.token, loadHome]);

  const handleLogout = () => {
    persistSession(null);
    setHomeMessage('');
    setHomeError('');
    navigate('/login');
  };

  const handleChangePassword = async () => {
    setNotice({ type: '', message: '' });
    try {
      const payload = await apiRequest('/api/auth/change-password', {
        method: 'POST',
        headers: authHeaders,
        body: JSON.stringify(changeForm),
      });
      setNotice({
        type: 'success',
        message: payload?.data?.message || '密码修改成功',
      });
      setChangeForm({ oldPassword: '', newPassword: '' });
      setChangeOpen(false);
    } catch (error: any) {
      setNotice({ type: 'error', message: error.message });
    }
  };

  const handleCloseChangeModal = () => {
    setChangeOpen(false);
    setNotice({ type: '', message: '' });
    setChangeForm({ oldPassword: '', newPassword: '' });
  };

  const activeMenu = useMemo(
    () => PATH_TO_MENU[location.pathname] ?? DEFAULT_MENU,
    [location.pathname],
  );
  const handleNavigate = useCallback(
    (key: MenuKey) => {
      const nextPath = MENU_ROUTES[key];
      navigate(nextPath);
    },
    [navigate],
  );
  const handleChangeField = useCallback(
    (field: ChangePasswordField, value: string) => {
      setChangeForm((prev) => ({ ...prev, [field]: value }));
    },
    [],
  );

  return (
    <Routes>
      {/* Guest routes (login/register) */}
      <Route element={<GuestRoute />}>
        <Route
          path="/login"
          element={
            <GuestLayout>
              <LoginPage onSuccess={onLoginSuccess} />
            </GuestLayout>
          }
        />
        <Route
          path="/register"
          element={
            <GuestLayout>
              <RegisterPage />
            </GuestLayout>
          }
        />
      </Route>

      {/* Protected routes (dashboard) */}
      <Route element={<ProtectedRoute />}>
        <Route
          path="/dashboard"
          element={
            <ProtectedLayout
              user={session ? { username: session.username } : null}
              activeMenu={activeMenu}
              onLogout={handleLogout}
              onChangePassword={() => setChangeOpen(true)}
              onNavigate={handleNavigate}
              changeOpen={changeOpen}
              changeForm={changeForm}
              onChangeField={handleChangeField}
              onChangePasswordSubmit={handleChangePassword}
              onCloseChangeModal={handleCloseChangeModal}>
              <Suspense fallback={<PageLoader />}>
                <HomePage
                  notice={notice}
                  homeMessage={homeMessage}
                  homeError={homeError}
                  username={session?.username}
                />
              </Suspense>
            </ProtectedLayout>
          }
        />
        <Route
          path="/users"
          element={
            <ProtectedLayout
              user={session ? { username: session.username } : null}
              activeMenu={activeMenu}
              onLogout={handleLogout}
              onChangePassword={() => setChangeOpen(true)}
              onNavigate={handleNavigate}
              changeOpen={changeOpen}
              changeForm={changeForm}
              onChangeField={handleChangeField}
              onChangePasswordSubmit={handleChangePassword}
              onCloseChangeModal={handleCloseChangeModal}>
              <Suspense fallback={<PageLoader />}>
                <UsersPage />
              </Suspense>
            </ProtectedLayout>
          }
        />
        <Route
          path="/roles"
          element={
            <ProtectedLayout
              user={session ? { username: session.username } : null}
              activeMenu={activeMenu}
              onLogout={handleLogout}
              onChangePassword={() => setChangeOpen(true)}
              onNavigate={handleNavigate}
              changeOpen={changeOpen}
              changeForm={changeForm}
              onChangeField={handleChangeField}
              onChangePasswordSubmit={handleChangePassword}
              onCloseChangeModal={handleCloseChangeModal}>
              <Suspense fallback={<PageLoader />}>
                <RolesPage />
              </Suspense>
            </ProtectedLayout>
          }
        />
        <Route
          path="/settings"
          element={
            <ProtectedLayout
              user={session ? { username: session.username } : null}
              activeMenu={activeMenu}
              onLogout={handleLogout}
              onChangePassword={() => setChangeOpen(true)}
              onNavigate={handleNavigate}
              changeOpen={changeOpen}
              changeForm={changeForm}
              onChangeField={handleChangeField}
              onChangePasswordSubmit={handleChangePassword}
              onCloseChangeModal={handleCloseChangeModal}>
              <Suspense fallback={<PageLoader />}>
                <SettingsPage />
              </Suspense>
            </ProtectedLayout>
          }
        />
      </Route>

      {/* Default redirect */}
      <Route path="/" element={<Navigate to="/login" replace />} />
      <Route path="*" element={<Navigate to="/login" replace />} />
    </Routes>
  );
}

export default App;

// Tigercat.Admin.Vue/src/App.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ConfigProvider, Container, Form, FormItem, Input, Modal, Message } from '@expcat/tigercat-vue'
import MainLayout from './components/MainLayout.vue'
import {
  SESSION_KEY,
  safeParse,
  apiRequest,
  type Session,
} from './utils'

const router = useRouter()
const route = useRoute()

const changeForm = ref({ oldPassword: '', newPassword: '' })
const session = ref<Session | null>(safeParse(localStorage.getItem(SESSION_KEY)) || null)

const homeMessage = ref('')
const loading = ref(false)
const homeError = ref('')
const changeOpen = ref(false)

const isAuthed = computed(() => Boolean(session.value?.token))
const authHeaders = computed(() => (session.value?.token ? { Authorization: `Bearer ${session.value.token}` } : {}))

// Track if we're on a protected route (dashboard)
const isProtectedRoute = computed(() => route.meta?.requiresAuth === true)

const persistSession = (nextSession: Session | null) => {
  if (!nextSession) {
    localStorage.removeItem(SESSION_KEY)
  } else {
    localStorage.setItem(SESSION_KEY, JSON.stringify(nextSession))
  }
  session.value = nextSession
}

const onLoginSuccess = async (nextSession: Session) => {
  persistSession(nextSession)
  await loadHome(nextSession.token)
  router.push({ name: 'dashboard' })
}

const loadHome = async (tokenOverride?: string) => {
  homeError.value = ''
  try {
    const payload = await apiRequest<string>('/api/home', {
      headers: tokenOverride ? { Authorization: `Bearer ${tokenOverride}` } : authHeaders.value,
    })
    homeMessage.value = payload?.data || ''
  } catch (error: any) {
    homeError.value = error.message
  }
}

const handleLogout = () => {
  persistSession(null)
  homeMessage.value = ''
  homeError.value = ''
  router.push({ name: 'login' })
}

const handleChangePassword = async () => {
  loading.value = true
  try {
    const payload = await apiRequest<{ message: string }>('/api/auth/change-password', {
      method: 'POST',
      headers: authHeaders.value,
      body: JSON.stringify(changeForm.value),
    })
    Message.success({
      content: payload?.data?.message || '密码修改成功',
      duration: 3000
    })
    changeForm.value = { oldPassword: '', newPassword: '' }
    changeOpen.value = false
  } catch (error: any) {
    Message.error({
      content: error.message,
      duration: 3000
    })
  } finally {
    loading.value = false
  }
}

// Load home data when entering dashboard
watch(
  () => route.name,
  (routeName) => {
    if (routeName === 'dashboard' && session.value?.token) {
      loadHome(session.value.token)
    }
  },
  { immediate: true }
)
</script>

<template>
  <ConfigProvider>
    <!-- Guest routes (login/register) -->
    <div v-if="!isProtectedRoute" class="min-h-screen bg-gradient-to-br from-slate-100 via-blue-50 to-indigo-100 p-6 flex items-center justify-center">
      <Container width="100%" :padding="false" class="w-full max-w-4xl">
        <RouterView @success="onLoginSuccess" />
      </Container>
    </div>

    <!-- Protected routes (dashboard) -->
    <MainLayout
      v-else
      :session="session"
      @logout="handleLogout"
      @change-password="changeOpen = true"
    >
      <RouterView
        :home-message="homeMessage"
        :home-error="homeError"
        :username="session?.username"
      />
        
      <Modal
        v-model="changeOpen"
        title="修改密码"
        ok-text="确认修改"
        cancel-text="取消"
        @ok="handleChangePassword"
        @cancel="changeOpen = false"
      >
        <Form :model="changeForm" :label-width="88">
          <FormItem name="oldPassword" label="旧密码">
            <Input
              v-model="changeForm.oldPassword"
              placeholder="请输入旧密码"
            />
          </FormItem>
          <FormItem name="newPassword" label="新密码">
            <Input
              v-model="changeForm.newPassword"
              placeholder="请输入新密码"
            />
          </FormItem>
        </Form>
      </Modal>
    </MainLayout>
  </ConfigProvider>
</template>
