// Tigercat.Admin.React/src/pages/ExceptionPage.tsx
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@expcat/tigercat-react/Button';
import { Result } from '@expcat/tigercat-react/Result';
import { Countdown } from '@expcat/tigercat-react/Countdown';
import { Empty } from '@expcat/tigercat-react/Empty';

type ExceptionStatus = 403 | 404 | 500;

interface ExceptionPageProps {
  status: ExceptionStatus;
}

const EXCEPTION_META: Record<
  ExceptionStatus,
  { status: '403' | '404' | '500'; title: string; subTitle: string }
> = {
  403: {
    status: '403',
    title: '无权访问',
    subTitle: '当前账号没有访问该页面的权限，请联系管理员分配。',
  },
  404: {
    status: '404',
    title: '页面不存在',
    subTitle: '访问的地址不存在或已被移动。',
  },
  500: {
    status: '500',
    title: '服务异常',
    subTitle: '演示场景：会话异常或服务请求失败时，可跳转到此页查看统一兜底。',
  },
};

export default function ExceptionPage({ status }: ExceptionPageProps) {
  const navigate = useNavigate();
  const meta = EXCEPTION_META[status];
  // 进入页面时仅初始化一次倒计时目标
  const countdownTarget = useMemo(() => Date.now() + 5000, []);
  const [autoJumpEnabled, setAutoJumpEnabled] = useState(status === 404);
  // React Router 把 idx 写进 history.state；未知路径走 Navigate replace 时
  // navigationType 是 REPLACE，但上一页仍在栈里，idx > 0 才能返回。
  const historyState = window.history.state as { back?: unknown; idx?: number; position?: number } | null;
  const canGoBack =
    historyState?.back != null ||
    (typeof historyState?.idx === 'number' && historyState.idx > 0) ||
    (typeof historyState?.position === 'number' && historyState.position > 0) ||
    window.history.length > 1;

  const goBack = () => {
    setAutoJumpEnabled(false);
    if (canGoBack) {
      navigate(-1);
    } else {
      navigate('/dashboard');
    }
  };

  return (
    <div className="min-h-screen bg-(--tiger-bg-page,#f8fafc) p-4 flex flex-col items-center justify-center">
      <div className="w-full max-w-md">
        <Result
          status={meta.status}
          title={meta.title}
          subTitle={meta.subTitle}
          extra={
            <div className="flex justify-center gap-2">
              <Button
                onClick={() => {
                  setAutoJumpEnabled(false);
                  navigate('/dashboard');
                }}
              >
                返回首页
              </Button>
              <Button variant="outline" onClick={goBack}>
                返回上一页
              </Button>
            </div>
          }
        >
          <div className="flex flex-col items-center">
            {status === 404 && autoJumpEnabled && (
              <Countdown
                value={countdownTarget}
                format="s"
                suffix="秒"
                title="即将自动返回首页"
                onFinish={() => navigate('/dashboard')}
              />
            )}
            {!canGoBack && (
              <Empty description="没有可返回的历史记录" showImage={false} />
            )}
          </div>
        </Result>
      </div>
    </div>
  );
}

// Tigercat.Admin.Vue/src/pages/ExceptionPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Button } from '@expcat/tigercat-vue/Button'
import { Result } from '@expcat/tigercat-vue/Result'
import { Countdown } from '@expcat/tigercat-vue/Countdown'
import { Empty } from '@expcat/tigercat-vue/Empty'

const props = defineProps<{
  status: 403 | 404 | 500
}>()

const router = useRouter()

const content = computed(() => {
  if (props.status === 403) {
    return {
      status: '403',
      title: '无权访问',
      subTitle: '当前账号没有访问该页面的权限，请联系管理员分配。',
    } as const
  }
  if (props.status === 404) {
    return {
      status: '404',
      title: '页面不存在',
      subTitle: '访问的地址不存在或已被移动。',
    } as const
  }
  return {
    status: '500',
    title: '服务异常',
    subTitle: '演示场景：会话异常或服务请求失败时，可跳转到此页查看统一兜底。',
  } as const
})

// Capture the countdown target once when the page is entered.
const countdownTarget = Date.now() + 5000
const autoJumpEnabled = ref(props.status === 404)
const canGoBack = computed(() => {
  const state = window.history.state as { back?: unknown; idx?: number; position?: number } | null
  if (state?.back != null) return true
  if (typeof state?.idx === 'number' && state.idx > 0) return true
  if (typeof state?.position === 'number' && state.position > 0) return true
  return window.history.length > 1
})

function goHome() {
  autoJumpEnabled.value = false
  router.push('/dashboard')
}

function goBack() {
  autoJumpEnabled.value = false
  if (canGoBack.value) {
    router.back()
  } else {
    router.push('/dashboard')
  }
}
</script>

<template>
  <div class="min-h-screen bg-(--tiger-bg-page,#f8fafc) p-4 flex flex-col items-center justify-center">
    <div class="w-full max-w-md">
      <Result :status="content.status" :title="content.title" :sub-title="content.subTitle">
        <template #extra>
          <div class="flex justify-center gap-2">
            <Button @click="goHome">返回首页</Button>
            <Button variant="outline" @click="goBack">返回上一页</Button>
          </div>
        </template>
        <div class="flex flex-col items-center">
          <Countdown
            v-if="status === 404 && autoJumpEnabled"
            :value="countdownTarget"
            format="s"
            suffix="秒"
            title="即将自动返回首页"
            @finish="goHome"
          />
          <Empty
            v-if="!canGoBack"
            class="mt-4"
            description="没有可返回的历史记录"
            :show-image="false"
          />
        </div>
      </Result>
    </div>
  </div>
</template>
