// Tigercat.Admin.React/src/pages/ForgotPasswordPage.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@expcat/tigercat-react/Button';
import { Card } from '@expcat/tigercat-react/Card';
import { Form } from '@expcat/tigercat-react/Form';
import { FormItem } from '@expcat/tigercat-react/FormItem';
import { Input } from '@expcat/tigercat-react/Input';
import { Message } from '@expcat/tigercat-react/Message';
import { Result } from '@expcat/tigercat-react/Result';
import { Steps, StepsItem } from '@expcat/tigercat-react/Steps';
import { Countdown } from '@expcat/tigercat-react/Countdown';
import { InputOTP } from '@expcat/tigercat-react/InputOTP';
import { MaskInput } from '@expcat/tigercat-react/MaskInput';
import {
  apiRequest,
  detectForgotChannel,
  isPhoneIdentity,
  OTP_LENGTH,
  OTP_RESEND_MS,
  PHONE_MASK,
} from '../utils';
import { LogoIcon } from '../components/Icons';

type ForgotStep = 0 | 1 | 2;

function ForgotPasswordPage() {
  const navigate = useNavigate();
  const [current, setCurrent] = useState<ForgotStep>(0);
  const [target, setTarget] = useState('');
  const [code, setCode] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [confirmError, setConfirmError] = useState('');
  const [targetError, setTargetError] = useState('');
  const [codeError, setCodeError] = useState('');
  const [loading, setLoading] = useState(false);
  const [codeLoading, setCodeLoading] = useState(false);
  const [codeDeadline, setCodeDeadline] = useState<number | null>(null);
  const [canResend, setCanResend] = useState(true);
  const [sentTo, setSentTo] = useState('');
  const usePhoneMask = isPhoneIdentity(target);

  const goToLogin = () => navigate('/login');

  const sendCode = async () => {
    const nextTarget = target.trim();
    if (!nextTarget) {
      setTargetError('请输入邮箱或手机号');
      return;
    }
    setTargetError('');
    setCodeLoading(true);
    try {
      const payload = await apiRequest<{ sentTo?: string }>('/api/auth/forgot-password/code', {
        method: 'POST',
        body: JSON.stringify({
          channel: detectForgotChannel(nextTarget),
          target: nextTarget,
        }),
      });
      setSentTo(payload?.data?.sentTo || nextTarget);
      setCanResend(false);
      setCodeDeadline(Date.now() + OTP_RESEND_MS);
      Message.success({ content: '验证码已发送至 ' + (payload?.data?.sentTo || nextTarget), duration: 2500 });
    } catch (error: any) {
      Message.error({ content: error.message, duration: 3000 });
    } finally {
      setCodeLoading(false);
    }
  };

  const submitIdentity = () => {
    if (!target.trim()) {
      setTargetError('请输入邮箱或手机号');
      return;
    }
    setTargetError('');
    if (!code.trim()) {
      setCodeError('请输入验证码');
      return;
    }
    setCodeError('');
    if (!sentTo) {
      Message.warning({ content: '请先获取验证码', duration: 2000 });
      return;
    }
    setCurrent(1);
  };

  const validatePasswords = () => {
    let valid = true;
    if (!password) {
      setPasswordError('请输入新密码');
      valid = false;
    } else if (password.length < 6) {
      setPasswordError('密码长度不能少于 6 位');
      valid = false;
    } else {
      setPasswordError('');
    }
    if (confirmPassword !== password) {
      setConfirmError('两次输入的密码不一致');
      valid = false;
    } else {
      setConfirmError('');
    }
    return valid;
  };

  const submitPassword = async () => {
    if (!validatePasswords()) return;
    setLoading(true);
    try {
      await apiRequest('/api/auth/forgot-password', {
        method: 'POST',
        body: JSON.stringify({
          channel: detectForgotChannel(target.trim()),
          target: target.trim(),
          code: code.trim(),
          password,
        }),
      });
      setCurrent(2);
    } catch (error: any) {
      Message.error({ content: error.message, duration: 3000 });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="flex flex-col md:flex-row w-full min-h-[500px] rounded-2xl overflow-x-clip overflow-y-visible shadow-lg border border-(--tiger-border,#e2e8f0)/30 bg-(--tiger-surface) animate-fade-in-up motion-reduce:animate-none"
      style={{
        '--tiger-primary': '#4f46e5',
        '--tiger-primary-hover': '#4338ca',
        '--tiger-primary-disabled': '#c7d2fe',
        '--tiger-focus-ring': '#4f46e5',
      } as React.CSSProperties}
    >
      <div className="hidden md:flex md:w-[42%] bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-600 p-8 flex-col justify-between text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-2xl -mr-20 -mt-20 pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-80 h-80 bg-blue-400/20 rounded-full blur-3xl -ml-32 -mb-32 pointer-events-none" />
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[size:20px_20px] pointer-events-none" />

        <div className="relative z-10">
          <div className="flex items-center gap-3 mb-8">
            <LogoIcon size={44} className="shadow-lg rounded-xl" />
            <span className="font-bold text-xl tracking-wider">Tigercat Admin</span>
          </div>
          <div className="space-y-6 my-auto pt-6">
            <h2 className="text-2xl font-bold leading-tight">找回账号访问权限</h2>
            <div className="space-y-4 text-pretty text-indigo-100 text-sm">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-white/15 text-white font-semibold">1</span>
                <span>验证邮箱或手机号身份</span>
              </div>
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-white/15 text-white font-semibold">2</span>
                <span>设置不少于 6 位的新密码</span>
              </div>
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-white/15 text-white font-semibold">3</span>
                <span>完成后返回登录页继续使用</span>
              </div>
            </div>
          </div>
        </div>

        <div className="relative z-10 text-xs text-indigo-200/80">
          © 2026 Tigercat Team. All rights reserved.
        </div>
      </div>

      <div className="w-full md:w-[58%] p-8 md:p-10 flex flex-col justify-center min-w-0">
        <div className="md:hidden flex items-center justify-center gap-3 mb-6">
          <LogoIcon size={48} className="shadow-md rounded-xl" />
          <h2 className="p2-text-primary text-xl font-bold">Tigercat Admin</h2>
        </div>

        <div className="mb-6 text-center md:text-left">
          <h1 className="p2-text-primary text-2xl font-bold tracking-tight">忘记密码</h1>
          <p className="p2-text-secondary text-sm mt-1">通过邮箱或手机号重置登录密码</p>
        </div>

        <div className="mb-6 overflow-x-auto">
          <Steps current={current} size="sm">
            <StepsItem title="验证身份" description="邮箱 / 手机号" />
            <StepsItem title="设置新密码" description="不少于 6 位" />
            <StepsItem title="完成" description="返回登录" />
          </Steps>
        </div>

        <Card variant="transparent" className="p-0">
          {current === 0 && (
            <Form value={{ target, code }} labelWidth={72} className="min-w-0">
              <FormItem name="target" label="账号">
                {usePhoneMask ? (
                  <div data-testid="forgot-phone-mask">
                    <MaskInput
                      value={target}
                      mask={PHONE_MASK}
                      placeholder="请输入邮箱或手机号"
                      status={targetError ? 'error' : undefined}
                      errorMessage={targetError}
                      onChange={(value) => {
                        setTarget(value);
                        if (targetError) setTargetError('');
                      }}
                    />
                  </div>
                ) : (
                  <Input
                    value={target}
                    placeholder="请输入邮箱或手机号"
                    status={targetError ? 'error' : undefined}
                    errorMessage={targetError}
                    onChange={(value) => {
                      setTarget(String(value));
                      if (targetError) setTargetError('');
                    }}
                  />
                )}
              </FormItem>
              <div className="mb-4 min-w-0 space-y-2">
                <p className="p2-text-primary text-sm">验证码</p>
                <div className="flex min-w-0 flex-col gap-3">
                  <div data-testid="auth-otp-input" className="flex min-w-0 w-full justify-start overflow-x-auto">
                    <InputOTP
                      value={code}
                      length={OTP_LENGTH}
                      size="sm"
                      type="numeric"
                      ariaLabel="验证码"
                      status={codeError ? 'error' : undefined}
                      errorMessage={codeError}
                      onChange={(value) => {
                        setCode(value);
                        if (codeError) setCodeError('');
                      }}
                    />
                  </div>
                  <div className="flex items-center gap-3 min-h-8">
                    {codeDeadline && !canResend ? (
                      <Countdown
                        value={codeDeadline}
                        format="s"
                        suffix="秒"
                        onFinish={() => setCanResend(true)}
                      />
                    ) : (
                      <Button
                        variant="outline"
                        size="sm"
                        loading={codeLoading}
                        type="button"
                        onClick={sendCode}
                      >
                        获取验证码
                      </Button>
                    )}
                  </div>
                </div>
              </div>
              {sentTo ? (
                <p className="p2-text-secondary mb-3 text-xs">验证码已发送至 {sentTo}</p>
              ) : null}
              <div className="mt-6 flex flex-col gap-3">
                <Button variant="primary" block type="button" onClick={submitIdentity}>
                  下一步
                </Button>
                <div className="text-center">
                  <button type="button" className="text-sm p2-text-secondary hover:underline" onClick={goToLogin}>
                    返回登录
                  </button>
                </div>
              </div>
            </Form>
          )}

          {current === 1 && (
            <Form value={{ password, confirmPassword }} labelWidth={88}>
              <FormItem name="password" label="新密码">
                <Input
                  value={password}
                  type="password"
                  placeholder="请输入新密码"
                  onChange={(value) => {
                    setPassword(String(value));
                    if (passwordError) setPasswordError('');
                  }}
                  status={passwordError ? 'error' : undefined}
                  errorMessage={passwordError}
                />
              </FormItem>
              <FormItem name="confirmPassword" label="确认密码">
                <Input
                  value={confirmPassword}
                  type="password"
                  placeholder="请再次输入新密码"
                  onChange={(value) => {
                    setConfirmPassword(String(value));
                    if (confirmError) setConfirmError('');
                  }}
                  status={confirmError ? 'error' : undefined}
                  errorMessage={confirmError}
                />
              </FormItem>
              <div className="mt-6 flex flex-col gap-3">
                <Button variant="primary" block loading={loading} type="button" onClick={submitPassword}>
                  重置密码
                </Button>
                <Button variant="outline" block type="button" onClick={() => setCurrent(0)}>
                  上一步
                </Button>
              </div>
            </Form>
          )}

          {current === 2 && (
            <Result
              status="success"
              title="密码已重置"
              subTitle="请使用新密码登录系统"
              extra={
                <Button variant="primary" onClick={goToLogin}>
                  返回登录
                </Button>
              }
            />
          )}
        </Card>
      </div>
    </div>
  );
}

export default ForgotPasswordPage;

// Tigercat.Admin.Vue/src/pages/ForgotPasswordPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Button } from '@expcat/tigercat-vue/Button'
import { Card } from '@expcat/tigercat-vue/Card'
import { Form } from '@expcat/tigercat-vue/Form'
import { FormItem } from '@expcat/tigercat-vue/FormItem'
import { Input } from '@expcat/tigercat-vue/Input'
import { Message } from '@expcat/tigercat-vue/Message'
import { Steps, StepsItem } from '@expcat/tigercat-vue/Steps'
import { Result } from '@expcat/tigercat-vue/Result'
import { Countdown } from '@expcat/tigercat-vue/Countdown'
import { InputOTP } from '@expcat/tigercat-vue/InputOTP'
import { MaskInput } from '@expcat/tigercat-vue/MaskInput'
import {
  apiRequest,
  detectForgotChannel,
  isPhoneIdentity,
  OTP_LENGTH,
  OTP_RESEND_MS,
  PHONE_MASK,
} from '../utils'
import AppLogo from '../components/AppLogo.vue'

const router = useRouter()
const current = ref(0)
const loading = ref(false)
const codeLoading = ref(false)
const target = ref('')
const code = ref('')
const password = ref('')
const confirmPassword = ref('')
const sentTo = ref('')
const targetError = ref('')
const codeError = ref('')
const passwordError = ref('')
const confirmError = ref('')
const canResend = ref(true)
const codeDeadline = ref<number | null>(null)

const usePhoneMask = computed(() => isPhoneIdentity(target.value))
const channel = computed(() => detectForgotChannel(target.value.trim()))

function startResendCountdown() {
  canResend.value = false
  codeDeadline.value = Date.now() + OTP_RESEND_MS
}

function validateIdentity(): boolean {
  targetError.value = ''
  const value = target.value.trim()
  if (!value) {
    targetError.value = '请输入邮箱或手机号'
    return false
  }
  return true
}

function validateCodeInput(): boolean {
  codeError.value = ''
  if (!code.value.trim()) {
    codeError.value = '请输入验证码'
    return false
  }
  return true
}

function validatePasswords(): boolean {
  passwordError.value = ''
  confirmError.value = ''
  if (!password.value) {
    passwordError.value = '请输入新密码'
    return false
  }
  if (password.value.length < 6) {
    passwordError.value = '密码长度不能少于 6 位'
    return false
  }
  if (password.value !== confirmPassword.value) {
    confirmError.value = '两次输入的密码不一致'
    return false
  }
  return true
}

async function sendCode() {
  if (!validateIdentity()) return
  codeLoading.value = true
  try {
    const payload = await apiRequest<{ sentTo: string }>('/api/auth/forgot-password/code', {
      method: 'POST',
      body: JSON.stringify({
        channel: channel.value,
        target: target.value.trim(),
      }),
    })
    sentTo.value = payload.data?.sentTo || target.value.trim()
    startResendCountdown()
    Message.success({
      content: '验证码已发送至 ' + sentTo.value,
      duration: 2500,
    })
  } catch (error: any) {
    Message.error({
      content: error.message,
      duration: 3000,
    })
  } finally {
    codeLoading.value = false
  }
}

function submitIdentity() {
  if (!validateIdentity() || !validateCodeInput()) return
  if (!sentTo.value) {
    Message.warning({
      content: '请先获取验证码',
      duration: 2000,
    })
    return
  }
  current.value = 1
}

async function submitPassword() {
  if (!validatePasswords()) return
  loading.value = true
  try {
    await apiRequest('/api/auth/forgot-password', {
      method: 'POST',
      body: JSON.stringify({
        channel: channel.value,
        target: target.value.trim(),
        code: code.value.trim(),
        password: password.value,
      }),
    })
    current.value = 2
  } catch (error: any) {
    Message.error({
      content: error.message,
      duration: 3000,
    })
  } finally {
    loading.value = false
  }
}

function goToLogin() {
  router.push({ name: 'login' })
}
</script>

<template>
  <div
    class="flex flex-col md:flex-row w-full min-h-[500px] rounded-2xl overflow-x-clip overflow-y-visible shadow-lg border border-(--tiger-border,#e2e8f0)/30 bg-(--tiger-surface) animate-fade-in-up motion-reduce:animate-none"
    style="--tiger-primary: #4f46e5; --tiger-primary-hover: #4338ca; --tiger-primary-disabled: #c7d2fe; --tiger-focus-ring: #4f46e5;"
  >
    <div class="hidden md:flex md:w-[42%] bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-600 p-8 flex-col justify-between text-white relative overflow-hidden">
      <div class="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-2xl -mr-20 -mt-20 pointer-events-none" />
      <div class="absolute bottom-0 left-0 w-80 h-80 bg-blue-400/20 rounded-full blur-3xl -ml-32 -mb-32 pointer-events-none" />
      <div class="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[size:20px_20px] pointer-events-none" />

      <div class="relative z-10">
        <div class="flex items-center gap-3 mb-8">
          <AppLogo :size="44" class="shadow-lg rounded-xl" />
          <span class="font-bold text-xl tracking-wider">Tigercat Admin</span>
        </div>
        <div class="space-y-6 my-auto pt-6">
          <h2 class="text-2xl font-bold leading-tight">找回账号访问权限</h2>
          <div class="space-y-4 text-pretty text-indigo-100 text-sm">
            <div class="flex items-center gap-3">
              <span class="flex items-center justify-center w-6 h-6 rounded-full bg-white/15 text-white font-semibold">1</span>
              <span>验证邮箱或手机号身份</span>
            </div>
            <div class="flex items-center gap-3">
              <span class="flex items-center justify-center w-6 h-6 rounded-full bg-white/15 text-white font-semibold">2</span>
              <span>设置不少于 6 位的新密码</span>
            </div>
            <div class="flex items-center gap-3">
              <span class="flex items-center justify-center w-6 h-6 rounded-full bg-white/15 text-white font-semibold">3</span>
              <span>完成后返回登录继续使用</span>
            </div>
          </div>
        </div>
      </div>
      <div class="relative z-10 text-xs text-indigo-200/80">
        © 2026 Tigercat Team. All rights reserved.
      </div>
    </div>

    <div class="w-full md:w-[58%] p-6 md:p-10 flex flex-col justify-center min-w-0">
      <div class="md:hidden flex items-center justify-center gap-3 mb-6">
        <AppLogo :size="48" class="shadow-md rounded-xl" />
        <h2 class="p2-text-primary text-xl font-bold">Tigercat Admin</h2>
      </div>

      <div class="mb-6 text-center md:text-left">
        <h1 class="p2-text-primary text-2xl font-bold tracking-tight">忘记密码</h1>
        <p class="p2-text-secondary text-sm mt-1">通过邮箱或手机号重置登录密码</p>
      </div>

      <Card variant="transparent" class="p-0">
        <div class="mb-6 overflow-x-auto">
          <Steps :current="current" size="sm">
            <StepsItem title="验证身份" description="邮箱 / 手机号" />
            <StepsItem title="设置新密码" description="不少于 6 位" />
            <StepsItem title="完成" description="返回登录" />
          </Steps>
        </div>

        <Form v-if="current === 0" class="min-w-0" :label-width="72">
          <FormItem label="账号">
            <div v-if="usePhoneMask" data-testid="forgot-phone-mask">
              <MaskInput
                :model-value="target"
                :mask="PHONE_MASK"
                placeholder="请输入邮箱或手机号"
                :status="targetError ? 'error' : undefined"
                :error-message="targetError"
                @update:model-value="(val: string) => { target = val; targetError = '' }"
              />
            </div>
            <Input
              v-else
              :model-value="target"
              placeholder="请输入邮箱或手机号"
              :status="targetError ? 'error' : undefined"
              :error-message="targetError"
              @update:model-value="(val: string) => { target = val; targetError = '' }"
            />
          </FormItem>
          <div class="mb-4 min-w-0 space-y-2">
            <p class="p2-text-primary text-sm">验证码</p>
            <div class="flex min-w-0 flex-col gap-3">
              <div data-testid="auth-otp-input" class="flex min-w-0 w-full justify-start overflow-x-auto">
                <InputOTP
                  :model-value="code"
                  :length="OTP_LENGTH"
                  size="sm"
                  type="numeric"
                  aria-label="验证码"
                  :status="codeError ? 'error' : undefined"
                  :error-message="codeError"
                  @update:model-value="(val: string) => { code = val; codeError = '' }"
                />
              </div>
              <div class="flex items-center gap-3 min-h-8">
                <Button
                  v-if="canResend || !codeDeadline"
                  variant="outline"
                  size="sm"
                  :loading="codeLoading"
                  type="button"
                  @click="sendCode"
                >
                  获取验证码
                </Button>
                <Countdown
                  v-else
                  :value="codeDeadline"
                  format="s"
                  suffix="秒"
                  size="sm"
                  @finish="canResend = true"
                />
              </div>
            </div>
          </div>
          <div class="mt-8 flex flex-col gap-3">
            <Button variant="primary" block type="button" @click="submitIdentity">下一步</Button>
            <button type="button" class="text-center text-sm font-medium text-[var(--tiger-primary,#3b82f6)] hover:underline" @click="goToLogin">返回登录</button>
          </div>
        </Form>

        <Form v-else-if="current === 1" :label-width="88">
          <FormItem label="新密码">
            <Input
              :model-value="password"
              type="password"
              placeholder="请输入新密码"
              :status="passwordError ? 'error' : undefined"
              :error-message="passwordError"
              @update:model-value="(val: string) => { password = val; passwordError = '' }"
            />
          </FormItem>
          <FormItem label="确认密码">
            <Input
              :model-value="confirmPassword"
              type="password"
              placeholder="请再次输入新密码"
              :status="confirmError ? 'error' : undefined"
              :error-message="confirmError"
              @update:model-value="(val: string) => { confirmPassword = val; confirmError = '' }"
            />
          </FormItem>
          <div class="mt-8 flex flex-col gap-3">
            <Button variant="primary" block :loading="loading" type="button" @click="submitPassword">重置密码</Button>
            <Button variant="outline" block type="button" @click="current = 0">上一步</Button>
          </div>
        </Form>

        <Result
          v-else
          status="success"
          title="密码已重置"
          sub-title="请使用新密码登录系统"
        >
          <div class="flex justify-center">
            <Button variant="primary" @click="goToLogin">返回登录</Button>
          </div>
        </Result>
      </Card>
    </div>
  </div>
</template>
